### ISSUE TITLE
"Show more" loses scroll position

### ISSUE THREAD

**Issue by dermike** [DagAgren/toot#100]
I love how Toot! remembers my scroll position and doesn't scroll to top when loading new data (even after being closed). Over night however there were a lot of new activity so there was a "show more" option between my last position and the new content. Tapping it made the timeline jump up to the newest toot of that load, so for me who prefers to always scroll up, this behaviour makes me have to scroll up and down, and try to remember where I last was.

It works so well within normal fetching, so I hope it can be made to work with "show more" as well!

**Comment by DagAgren** [comment]
https://github.com/DagAgren/toot/issues/54
