### ISSUE TITLE
Transparent tab bar on iPad

### ISSUE THREAD

**Issue by volkerv** [DagAgren/toot#102]
Toot 1.0(25)

On an iPad4 running **iOS 10** the bottom tab bar is transparent.
You can still tap on the tabs but the timeline shines through.

![img_0035](https://user-images.githubusercontent.com/6153190/44258379-0496c900-a20f-11e8-9d15-54632b094615.PNG)

**Comment by tonilampela** [comment]
I’m seeing possibly a variation of this bug also with iPad on iOS 12 beta. Tab bar becomes transparent and elements of the tab bar shift around.
