### ISSUE TITLE
Image rotation

### ISSUE THREAD

**Issue by MarcusP-P** [DagAgren/toot#106]
I tried to upload some photos from an iPad to Mastodon.social using Toot!, but the images appear to be rotated incorrectly. I’m not sue if this is a server side bug or a Toot! Bug

**Comment by DagAgren** [comment]
It may be that the images are using the JPEG rotation tag instead of actually being rotated, and somewhere along the line that tag is being ignored. Could you upload some example images for this?

**Comment by derkatron** [comment]
I can.

So here's the picture:
![img_1244](https://user-images.githubusercontent.com/42478053/45919237-16980700-be60-11e8-812b-8dc0d3546d6b.JPG)

Here it is on the timeline in Toot!:
![img_1246](https://user-images.githubusercontent.com/42478053/45919242-2a436d80-be60-11e8-8021-b2f8255080bb.PNG)

Here it is on the instance's homepage:
![screenshot 2018-09-22 at 12 09 43](https://user-images.githubusercontent.com/42478053/45919260-81494280-be60-11e8-9a59-0576d1233e50.png)

Here it is when you click on the image:
![screenshot 2018-09-22 at 12 11 19](https://user-images.githubusercontent.com/42478053/45919273-aa69d300-be60-11e8-804b-4dd4f7c6305d.png)

And here it is on the URL for the toot itself:
![screenshot 2018-09-22 at 12 12 37](https://user-images.githubusercontent.com/42478053/45919281-dd13cb80-be60-11e8-8f81-4d99646cc76d.png)

**Comment by DagAgren** [comment]
I think this was fixed already?
