### ISSUE TITLE
Glitchy instance description scrolling for chaos.social

### ISSUE THREAD

**Issue by lutoma** [DagAgren/toot#107]
Screencast at https://fnord.cloud/s/bPA3eWciQgtFLCZ - Only the initial scroll downwards is manual, the remaining glitching happens without input. iOS 12 on an iPhone 8.

Not sure if this affects other instances and what exactly causes this. Maybe because of the rather short description length (compared to other instances?).

**Comment by jconnary** [comment]
Verified behaviour on multiple instances.

**Comment by DagAgren** [comment]
Any chance of confirming if it happens on iOS 11? I don't want to spend time on investigating things that may just be iOS 12 bugs.

**Comment by jconnary** [comment]
Sorry I don't have devices running 11.

**Comment by digitalscofflaw** [comment]
It's happening on 11.4.1 on my 6S Plus.
