### ISSUE TITLE
Toot! should always refresh timelines when app loads

### ISSUE THREAD

**Issue by billsaysthis** [DagAgren/toot#109]
This seems pretty clear to me and really important, why would I need to pull to refresh every time I open the app?

**Comment by DagAgren** [comment]
Refreshing behaviour is not fully implemented yet.

**Comment by mediaformat** [comment]
This should be an option.
It’s actually useful NOT to refresh, sometimes one can be interrupted, and want to resume interactions from where one left off. Thanks

**Comment by DagAgren** [comment]
Toot already refreshes when the app starts. Resuming always works, as timeline positions are remembered.
