### ISSUE TITLE
Emojo selector

### ISSUE THREAD

**Issue by DagAgren** [DagAgren/toot#11]
The posting screen needs a way to select custom emoji.

**Comment by darrenpmeyer** [comment]
It would be very nice if the Slack-like behavior of being able to type :emojo_name: and have suggestions available were part of this feature. I often know which I want but can't recall the exact name

**Comment by DeeRah** [comment]
Will we be able to select custom emojis soon ?

**Comment by Tealk** [comment]
That was never built in?

**Comment by chucker** [comment]
It was added in fall. (Note this is for _custom_ emojo, not regular OS emoji.)
