### ISSUE TITLE
Done boosts/favorites are disappearing

### ISSUE THREAD

**Issue by myhubacct** [DagAgren/toot#112]
If I boost or favorite a toot, than the text button(s) will shown up in bold. As sonn as I refreshing the timeline it virtually disappears, means the text becomes normal strength and I get lead into the opinion not already act on the toot or lost my actions. 

iOS 11.4.1 (15g77)
Toot! Beta 1.0(25)
iPhone 6

**Comment by jconnary** [comment]
I can confirm this. I boosted a toot and the text turned to Boosted. I refreshed my home timeline and the text returned to Boost instead of Unboost.

iOS 12 PB6, iPhone 7+

**Comment by DagAgren** [comment]
There is no "boosted" text in the app, and no bold state.

Maybe you accidentally enabled "Double tap to boost", in which case tapping boost does not actually boost the toot until you tap it a second time, and it will instead become bigger?

**Comment by myhubacct** [comment]
Thank you for looking into that ticket. Have done the sequence again and the behavior is still there. 

- open detail of a toot from Lokal time line 
- boost that toot with button “BOOST”
-> works, button changing to “UNBOOST”

- switching back to the Lokal time line
-> button of that toot is changing back to “BOOST” instead of staying with the text “UNBOOST”

- check my Toot! Home page. The boosted toot is there and the button is set to “UNBOOST”

It is a bit confusing that the local time line shows different state of the toot then the home page.

**Comment by myhubacct** [comment]
Forgot to tell, the function “Double tab to boost” is not enabled. Have just checked it now.
