### ISSUE TITLE
Unable to log in to my self-hosted instance

### ISSUE THREAD

**Issue by waferbaby** [DagAgren/toot#115]
Hola!

I'm on v1.0 (29). I run my own Mastodon instance on waferbaby.com (v2.4.3, the main branch, no edits). I can add my instance fine, view all the toots on the local timeline, etc, and if I go to sign in, I get the normal web flow, authenticate, am asked to confirm I want to allow Toot! to access my account, all good.

Soon as I allow it, however, I get "Wrong password or email". If I then try to re-auth, it loads the web view for a second, then I get the same.

If I look on the server, I see the authed app is in my account, etc. In the server logs, I'm seeing:

```
118.209.192.226 - - [19/Aug/2018:14:28:11 -0700] "GET /sw.js HTTP/2.0" 304 0 "https://waferbaby.com/sw.js" "Mozilla/5.0 (iPhone; CPU iPhone OS 11_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1"
118.209.192.226 - - [19/Aug/2018:14:28:11 -0700] "GET /oauth/authorize?client_id=(client id)&redirect_uri=cx-c3-toot://authorised/0&response_type=code&scope=read+write+follow+push HTTP/2.0" 302 157 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 11_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1"
```

Any ideas why it might be choking here? I've successfully tested it with other iOS apps, FWIW.

Worth noting: my server supports HTTP/2.

**Comment by waferbaby** [comment]
(If it would help, I can set you up an account on there.)

**Comment by csabyka** [comment]
same as in my instance

**Comment by emmawinston** [comment]
I am currently getting the same 'Wrong password or email' after the same flow of authenticating and confirming on mastodon.social, bizarrely, but no other instance. 

Obviously can't look under the hood to see if the server logs match in my case though.

**Comment by mattjeffryes** [comment]
I am having the same issue with mastodon.social as @emmawinston

**Comment by joshpuetz** [comment]
Unable to log into mastodon.social or ruby.social here as well with v1.0(29

**Comment by 4gra** [comment]
Tried reverting to 1.0 (25); same issue.

**Comment by splorp** [comment]
Likewise. Same authentication flow errors as described above.

@splorp@mastodon.social

**Comment by splorp** [comment]
I’m using a fairly generic gmail.com address.

**Comment by mattjeffryes** [comment]
Working for me in 32.

**Comment by waferbaby** [comment]
Looks like 32 fixed it, yay!
