### ISSUE TITLE
Show/Hide Boosts

### ISSUE THREAD

**Issue by hackertours** [DagAgren/toot#117]
Hello :) The timeline is currently a mess because of the massive amounts of boosts. The default web interface allows hiding boosts. That would be a very nice setting for Toot!.

**Comment by a-dows** [comment]
Seconding to improve party with the web interface.

I have an account that's primarily for close friends, and I hide boosts on that timeline so I can see only what they are personally saying, leaving memes to my main account. I'd really value this feature in Toot!.

**Comment by DagAgren** [comment]
As far as I can tell, there is no backend support for this, and it is done via local filtering of the timeline. Due to the architecture of the timeline caching in Toot!, it's really inefficient to try to filter out entries in the timeline, so I don't think I will be able to add this any time soon.
