### ISSUE TITLE
Scroll position and image behavior

### ISSUE THREAD

**Issue by seik** [DagAgren/toot#118]
Video: https://youtu.be/Le0KLG1uMZ4
Toot showed in the video: https://mastodon.technology/@n/100579155265408051

I thought about creating two separate issues but since I'm not sure this are two separate bugs...

I got to reproduce once the photo bug with the scroll position being respected so I think the scroll position has to do with the vertical size of the image.

**Comment by DagAgren** [comment]
This is probably related to https://github.com/DagAgren/toot/issues/53.

**Comment by DagAgren** [comment]
I *think* I have fixed this now, so I am closing the issue, but do post here immediately if you see it happening again after the next release!
