### ISSUE TITLE
Sub profile following list is not displayed 

### ISSUE THREAD

**Issue by pudility** [DagAgren/toot#119]
When I click on someone's profile, then the following button, then a profile from that table view, then the following button only the common followings are displayed. In the below video, you can see that the sub-profile I click *should* have 122 followings but only has 2 displayed. 

[Video is inside zip because github does not like videos. ](https://github.com/DagAgren/toot/files/2301060/ScreenRecording_08-19-2018.20-31-22.MP4.zip)

**Comment by DagAgren** [comment]
I think this is a server-side issue, where any given instance may not have all the accounts of the followers.
