### ISSUE TITLE
CW construction site styling is difficult to read

### ISSUE THREAD

**Issue by lamnatos** [DagAgren/toot#120]
Seen on v1.0 (29)

The new styling of the CW description is difficult to read, especially on long-form descriptions which are not rare to occur.

Please consider a more subtle effect that's easier on the eyes and makes the text more legible.

Example:

![toot_cw](https://user-images.githubusercontent.com/178458/44324491-56289900-a445-11e8-996d-49f1165bf9ac.jpg)

**Comment by DagAgren** [comment]
Tried a toned down version, let's see how it goes over.
