### ISSUE TITLE
[Accessibility] Condense the VoiceOver reading order into one swipe for each toot, and make all tapable items into AccessibilityCustomActions.

### ISSUE THREAD

**Issue by MarcoZehe** [DagAgren/toot#124]
Right now, each toot is at least 6 swipes before a VoiceOver user gets to the next toot. If you want to read a busy timeline, that's a lot of swipes, and a lot of repeats of "Reply, "Boost", "Favourite" etc., making reading toots very inefficient. Here's how to improve this:

1. Make all the elements like images, profile button, reply, boost and favourite buttons IsAccessibilityElement "No", effectively removing them from VoiceOver's view.
2. On the element that remains, add an [array of AccessibilityCustomActions](https://developer.apple.com/documentation/uikit/accessibility/uiaccessibilityaction) that contains all actions one can perform on a toot as a sighted user. VoiceOver will pick these up automatically and inform the user. The user then swipes up and down to select the action and double-taps to activate that action.

Actions should include, in roughly this order:

- Default, whatever tapping on non-linked text does, like revealing a CW hidden toot, or opening the thread.
- User names that can be tapped in the toot, for example if someone is mentioned.
- Any links that are in there.
- Any images that are in there and can be opened.
- The Reply action.
- The Boost action.
- The Favourite action.
- The From: Profile to open.
- The Boosted by profile (if present) to open.

Note that users can also swipe up from the Default action to wrap to the bottom, so even on a busy toot, the From is one, or if this is a boost, two swipes away.

This would make reading toots and interacting with them much more efficient, and it would guarantee that all items in a toot are accessible and would open correctly.

**Comment by DagAgren** [comment]
Ooh, that is some good information.

**Comment by DagAgren** [comment]
After a lot of work I have managed to implement a lot of this functionality on most cell types. Not quite everything is there but I think it will do for a first attempt.
