### ISSUE TITLE
instance wheel hard to operate on iphone X

### ISSUE THREAD

**Issue by samdmarshall** [DagAgren/toot#128]
the position and gestures associated with the instance wheel makes it really difficult to use on an iphone x due to the positioning of the bottom grab bar that the system provides.

from an accessibility standpoint, i would like a different way to interact with swapping instances as this one is really difficult for me.

**Comment by DagAgren** [comment]
Personally I very rarely get the wrong action. The wheel controls are quite forgiving on purpose to make this easier to do.

There might be a long press menu or something in the future, but it is not a priority at the moment.
