### ISSUE TITLE
content warning toggle hit box is tiny

### ISSUE THREAD

**Issue by samdmarshall** [DagAgren/toot#129]
when a toot has a cw over it, you can tap anywhere to reveal it then the only place to tap to re-toggle is the bar at the top of the toot. the height of the bar is small and can be easy to hit the name of the person the foot is from (or even the actions of the toot above it) or the toot body itself; both of which take you away to separate screens.

**Comment by DagAgren** [comment]
I am assuming people don't do this very often, and I don't want to sacrifice any other functionality for this, so I think it is fine as is.

**Comment by samdmarshall** [comment]
could you make the default bar height just a bit taller? that shouldn't need any sacrifice in functionality.
