### ISSUE TITLE
Stuck trying to boost any toot

### ISSUE THREAD

**Issue by lucascantor** [DagAgren/toot#130]
I'm currently unable to boost any toots.

The `BOOST` button gets stuck in a "tapped" state, without my boost actually happening:

[**Screen recording of the issue being reproduced**](https://i.imgur.com/QMT0FVK.mp4)

**Comment by DagAgren** [comment]
You have enabled double tap to boost. Turn it off, or tap twice.

**Comment by lucascantor** [comment]
Oops 😬

I didn’t realize the two modes were mutually exclusive. My mistake. Thanks so much for the quick follow up 👍🏼
