### ISSUE TITLE
"Failed to load instance data" on initial add of instance

### ISSUE THREAD

**Issue by rakslice** [DagAgren/toot#131]
When setting up Toot! for the first time, when I try to add the instance I usually use (`mastodon.club`), I get this error:

> Failed to load instance data
> 
> The data couldn't be read because it is missing. (No value associated with key CodingKeys(stringValue: "urls", intValue: nil) ("urls").)

![0](https://user-images.githubusercontent.com/1845104/44379879-e229d780-a4bc-11e8-9b4c-46abfe282bac.png)

There's good wifi connectivity. My setup is pretty vanilla point of view; there's no proxy or VPN, and I use this same instance from other Mastodon clients on the same device.

TestFlight indicates this is Toot! "Version 1.0 (29)"

**Comment by DagAgren** [comment]
Sounds like the instance is weird somehow and is not returning a valid description of itself.

**Comment by rakslice** [comment]
Investigating further: Is this just the `GET /api/v1/instance` request? It gives me a response to that; note that it is version 1.4.1 which gives less info. Does Toot! have a minimum compatible server version?

**Comment by DagAgren** [comment]
On Tue, Aug 21, 2018 at 11:05 PM rakslice <notifications@github.com> wrote:
>
> Investigating further: Is this just the GET /api/v1/instance request? It gives me a response to that; note that it is version 1.4.1 which gives less info. Does Toot! have a minimum compatible server version?

It definitely expects a very recent version. Pre-2.0 absolutely won't
work, not sure if it needs to be any newer.

-- 
Dag Agren <> paracelsus@gmail.com <> http://wakaba.c3.cx/

**Comment by rakslice** [comment]
Ah, ok.
