### ISSUE TITLE
Remove the instance rotation wheel

### ISSUE THREAD

**Issue by truhe2342** [DagAgren/toot#133]
The instance rotation wheel is hard to use, not usable for lefties, triggers the iOS "swipe from bottom" and you have to understand what it does and how fast you have to swipe to make it work good. A better and well-known solution would be to replace it with the common tap-and-hold-menu, like Tweetbot does. While I do like the optical effect and that it shows the instance name (sort of), I don't think that the things working not good with it are fixable and should be fixed, when there are solutions out there which users know and work well.

**Comment by DagAgren** [comment]
Sorry, not happening. Some issues will have fixes for them, though.
