### ISSUE TITLE
OpenGraph/Twitter URL preview layout

### ISSUE THREAD

**Issue by mediaformat** [DagAgren/toot#134]
The title and description seem to go off screen, ultimately the width should be same as app. 

Screenshot from iPhone6
![0db46273-34b5-4721-977d-4e5616975f13](https://user-images.githubusercontent.com/2895351/44415213-dcc0a180-a53d-11e8-993a-14972bb9c19b.png)

**Comment by DagAgren** [comment]
Does this still reproduce? I've never seen it, and I have rewritten some of this code so I am going to optimistically close the issue and hope it got accidentally fixed, whatever it was.
