### ISSUE TITLE
Errors viewing profiles on instances running Mastodon 2.0.0

### ISSUE THREAD

**Issue by alahmnat** [DagAgren/toot#138]
I'm unable to follow or use the "MORE..." menu with users on instances running Mastodon 2.0.0 by viewing their profile. The profile view shows the following error:

"The data couldn't be read because it is missing (No value associated with key CodingKeys(stringValue: "muting_notifications", initValue: nil) ("muting_notifications").) Index 0"

I don't remember when muting was added to Mastodon, but I'm guessing it was after 2.0 and Toot! isn't gracefully handling the feature's absence.

**Comment by DagAgren** [comment]
Not entirely sure how much I want to support outdated instances.
