### ISSUE TITLE
Display the number of unread toots

### ISSUE THREAD

**Issue by bviefhues** [DagAgren/toot#140]
Would be great to have a counter for unread toots, i.e. number of toots from current position to head of timeline. Tweetbot does this and I really like that.

**Comment by DagAgren** [comment]
This information isn't readily available (since toots are loaded in batches, and all of them won't be loaded), so it probably won't happen.

**Comment by georgehrke** [comment]
@DagAgren Since mastodon is a cool open project it's perhaps worth creating a feature request upstream to ask for including the number of leftover status after this batch?
(Should I create a feature request for that?)
