### ISSUE TITLE
„Twitter“ Keyboard 

### ISSUE THREAD

**Issue by gerdemann** [DagAgren/toot#146]
Use Twitter keyboard instead of the normal one. Then you can write hashtags simpler.

**Comment by DagAgren** [comment]
Tried adding it, let's see how it goes!

**Comment by chipotle** [comment]
The Twitter keyboard has no return key, so it's impossible to make a post that has multiple lines in it. I do this all the time, and while it's possible I'm just a weirdo, a check just now shows around 30% of the toots on my timeline have carriage returns in them. I get that the normal keyboard makes the @ and # characters a little harder to type, but it looks like the Twitter keyboard makes the return key *impossible* to type.

**Comment by DagAgren** [comment]
It does, you just have to go to the numbers page.

I might consider adding a tweak setting for it, but we'll see.
