### ISSUE TITLE
Cannot display the entirety of long bios

### ISSUE THREAD

**Issue by huxinq** [DagAgren/toot#149]
I think there's currently no way to view a long bio in its entirety in the app.
![img_6097](https://user-images.githubusercontent.com/14837634/44628698-b0f74e80-a977-11e8-958d-888cb69cbe58.jpg)

**Comment by slice** [comment]
Duplicate of #77 👀

**Comment by huxinq** [comment]
Oops, should’ve done more searching.  Sorry.
