### ISSUE TITLE
Handle unsupported instances better

### ISSUE THREAD

**Issue by pvanb** [DagAgren/toot#150]
When adding an old instance (#147) or using a feature that isn’t available on an instance (#138) the user is presented with an error that looks to the user like the app is broken.

The user should either be prevented from adding unsupported instances with a user-friendly message, or if the instance is added then  unsupported features should either  be disabled or fail with a user-friendly message.

**Comment by DagAgren** [comment]
Not sure if this is really relevant any more. I think most instance should have upgraded by now.
