### ISSUE TITLE
"Show more" moves timeline

### ISSUE THREAD

**Issue by MoritzFago** [DagAgren/toot#153]
Current behavior: If you press the "show more" button, that appears if toot didn't load all the toots, the timeline moves somewhere else.

Fix: don't move the timeline, just add the toots above or below, but make sure that some of the surrounding toots stay visible.

**Comment by aharpole** [comment]
Maybe the behavior can depend on the position of the “show more” button when it was pressed? I.e. if it was near the top of the screen, insert the filled in toots above it, and vice versa.

**Comment by MoritzFago** [comment]
@aharpole it could, just make it so that at least one end doesn't move
