### ISSUE TITLE
Consider defaulting toot button to text

### ISSUE THREAD

**Issue by chipotle** [DagAgren/toot#154]
While the popup UI for "text / library / camera / video" toot kinds is really clever, I'm not sure it's ideal UX in terms of speed. If it defaulted to a text toot, users would be able to start composing toots with one tap instead of two -- and since "library", "camera", and "snap video" are at the bottom of the text field, it'd still only be two taps if I wanted to switch to those. This seems like a minor thing, but I suspect the text-only toot is far and away the most common, so perhaps the interface should be optimized for that use case.

**Comment by DagAgren** [comment]
You can currently tap and slide to select an option without a second tap.
