### ISSUE TITLE
Keyboard entry doesn’t allow “Return” key 

### ISSUE THREAD

**Issue by philippec** [DagAgren/toot#158]
When I type a Toot, the keyboard doesn’t show the “return” key to allow me to separate paragraphs. Instead of Return it shows the @ sign so perhaps it’s just the wrong keyboard type.

**Comment by tychoquad** [comment]
It’s intentional. It’s now using the twitter keyboard which gives you the @ and # for replies and tagging. These should become more useful when username and hashtag autocomplete is in.

The return key is still there on the number page. (The 123 button in the bottom left)

**Comment by philippec** [comment]
Great! Thanks for the explanation.
