### ISSUE TITLE
iPhone X: tab bar display corruption upon rotation during full size image display

### ISSUE THREAD

**Issue by ahndee** [DagAgren/toot#162]
On the iPhone X, perform the following steps:

1. In Portrait mode, tap on an image to show full screen
2. Rotate to landscape mode
3. Dismiss the full screen image

-> The tab bar is completely messed up:

![img_3550](https://user-images.githubusercontent.com/66345/44829646-9f5db300-abd2-11e8-83b9-427cb38f8abc.png)

**Comment by DagAgren** [comment]
Haven't decided yet if I am going to support landscape mode yet, so I am not sure if this needs fixing.
