### ISSUE TITLE
Not launching on iPhone 5s, iOS 10

### ISSUE THREAD

**Issue by narFnarF** [DagAgren/toot#165]
The app always crashes about 3 seconds after launching, while on the splash screen.

**Repro steps:**

1. Launch app
2. Observe crash while on the "Toot!" splash screen

**Repro rate:** 100% (10/10)

**Version :** 1.0 (35) from TestFlight

**Device:** iPhone 5s, iOS 10.3.3

**Comment by MichielBijl** [comment]
I’m getting the same on an iPhone X running iOS 12. Although it crashes a lot faster. I’m also running version 35. I’m not sure how to provide a crash log.

**Comment by Kelloggs** [comment]
I can confirm this issue on a iPhone Xs running iOS 12 with version 35.

**Comment by DagAgren** [comment]
Those are some kind of different crash, so please file a different issue, especially if you can figure out any other details.

**Comment by WinterMagik** [comment]
App just freezes and doesnt launch at all on my phone.

IOS 10, iphone 5. Any ETA when an update will come out to fix this by chance?

BTW if you need beta testers I can help if you'd like :)

**Comment by DagAgren** [comment]
I could easily disable the crashing part, I think, but I can't quite figure out on which phones it needs disabling and how to detect it. Hmm...

**Comment by DagAgren** [comment]
I could try disabling it on iOS 10. Probably most devices that are stuck on iOS 10 will be the same ones that struggle to show this.
