### ISSUE TITLE
Feature request: setting to always open URLs in Safari

### ISSUE THREAD

**Issue by wka** [DagAgren/toot#167]
Tapping a URL currently opens it in an in-app webview/SFSafariViewController.

It would be great to be able to always open URLs in Safari.  This would be very helpful when running Safari alongside Toot via iPad multitasking.

**Comment by wka** [comment]
(I realize I can open in Safari by tapping and holding, then selecting Open in Safari.  A setting to always open in Safari would be more straightforward to use.)

**Comment by dahlia** [comment]
It would be great if Toot has browser settings — I want to open links using Firefox.  Indeed quite many iOS apps has the same thing.  E.g.:

### Tweetbot

<div><img src="https://user-images.githubusercontent.com/12431/46594935-e3689f80-cb10-11e8-82df-82b48da24625.PNG" width="50%"><img src="https://user-images.githubusercontent.com/12431/46594936-e4013600-cb10-11e8-9aca-082821e71080.PNG" width="50%"></div>

### IRCCloud

<div><img src="https://user-images.githubusercontent.com/12431/46594989-2b87c200-cb11-11e8-9117-ff999452050e.PNG" width="50%"><img src="https://user-images.githubusercontent.com/12431/46594990-2b87c200-cb11-11e8-997c-4874b12301ba.PNG" width="50%"></div>

### Slack

<div><img src="https://user-images.githubusercontent.com/12431/46595035-6db10380-cb11-11e8-9e96-5edf395f311d.PNG" width="50%"><img src="https://user-images.githubusercontent.com/12431/46595036-6e499a00-cb11-11e8-9672-6e1f27679471.PNG" width="50%"></div>

### Reddit

<div><img src="https://user-images.githubusercontent.com/12431/46595033-6db10380-cb11-11e8-8b4d-58f6e95bd0b7.PNG" width="50%"><img src="https://user-images.githubusercontent.com/12431/46595034-6db10380-cb11-11e8-879f-364e20f84311.PNG" width="50%"></div>
