### ISSUE TITLE
Thumbnail image appears for a split second after swiping away image.

### ISSUE THREAD

**Issue by jamieforrest** [DagAgren/toot#170]
### Steps to reproduce
1) Find a toot with an image attachment
2) Tap on the image
3) Swipe away the image

### Results
Expected: Image goes away and timeline appears.
Actual: Image thumbnail appears toward the top of the timeline for a split second, then goes away.

### Notes
Video of the bug is [here](https://pgh.social/@jamie/100668482658540726).

**Comment by DagAgren** [comment]
Possibly related to https://github.com/DagAgren/toot/issues/53

**Comment by DagAgren** [comment]
I *think* I have fixed this now, so I am closing the issue, but do post here immediately if you see it happening again after the next release!
