### ISSUE TITLE
Allow users to disable "twitter" keyboard

### ISSUE THREAD

**Issue by revi** [DagAgren/toot#175]
Please provide a way to disable #146 - I'm from the birdsite app "Tweetbot" which does not have that "Twitter" keyboard, and it's annoying that I have to go to '123' view to press 'enter'.

**Comment by DagAgren** [comment]
I'm considering it, we'll see. Also, the Twitter keyboard does have some intelligence to help with this. After full sentences, the enter button is shown.

**Comment by revi** [comment]
> Also, the Twitter keyboard does have some intelligence to help with this. After full sentences, the enter button is shown.

Never seen that — If I end the sentence with '.' I already have access to 'return' key and when I use Korean keyboard I usually don't use '.'

**Comment by DagAgren** [comment]
Added an option to disable the twitter keyboard, and also made the twitter keyboard a bit more clever about newlines.
