### ISSUE TITLE
Delete & re-draft

### ISSUE THREAD

**Issue by DagAgren** [DagAgren/toot#177]

**Comment by tychoquad** [comment]
I would like delete and redraft better if links to the original toot redirected to the new one. Nothing quite like writing a long toot, submitting, creating a link to it on twitter, and then have to delete that tweet and relink to it after noticing a spelling error in your toot and correcting it

**Comment by DagAgren** [comment]
Toot! has no control over that, unfortunately. You can try requesting it from Mastodon.

**Comment by DagAgren** [comment]
Depends on https://github.com/DagAgren/toot/issues/208
