### ISSUE TITLE
Notifications: '<' recognised as HTML Tag

### ISSUE THREAD

**Issue by PhilippvK** [DagAgren/toot#185]
I've found another example for sightly wrong handling of HTML tags in notifications.

The character `<` is not displayed in the iOS notification, if used in a toot.

Original Toot:
![img_6591-1](https://user-images.githubusercontent.com/7712605/45924806-d3966c00-bf11-11e8-9759-43862a0a4436.jpg)

Notification Screenshot:
![img_6565-1](https://user-images.githubusercontent.com/7712605/45924808-d5602f80-bf11-11e8-83ab-d0ad3edd77d3.jpg)

This is not very urgent, but I open this Issue just to document it. Maybe it can be handled similar to #104. Thank you.

**Comment by fluffy-critter** [comment]
I’m running into this too. Example toot: https://queer.party/@fluffy/102367850079697491
![01406CF0-60A2-403C-95D3-40475617CB8A](https://user-images.githubusercontent.com/347162/60466897-d3966b80-9c09-11e9-9427-957778469188.png)

**Comment by fluffy-critter** [comment]
I’m running into this too. Example toot: https://queer.party/@fluffy/102367850079697491 (the `<details>` is being stripped out)

![6688BBF5-E416-4A1B-AC02-E08FCCB66C79](https://user-images.githubusercontent.com/347162/60466962-0b9dae80-9c0a-11e9-905e-434288e39e86.png)

**Comment by DagAgren** [comment]
This seems to have got fixed server-side while I was ignoring it?
