### ISSUE TITLE
Crash on launch iOS 12 / iPhone X

### ISSUE THREAD

**Issue by MichielBijl** [DagAgren/toot#187]
Repro steps:

- Launch app
- Observe crash while on the "Toot!" splash screen
Repro rate: 100% (10/10)

Version : 1.0 (35) from TestFlight

Device: iPhone X, iOS 12

**Comment by DagAgren** [comment]
That's weird, I don't see any crash reports for this at all.

**Comment by DagAgren** [comment]
Do you have reporting crashes to Apple enabled?

**Comment by TimeDoctor** [comment]
I believe I have the same crash on iOS 12/iPhone X. Not sure how useful it is, but here’s a video: https://youtu.be/HMO79tGsL5U

**Comment by DagAgren** [comment]
This seems to be a weird Apple bug: https://mastodon.social/@davewoodx/100805692906874770
