### ISSUE TITLE
Tapping UIBarButtonItem on the UIToolbar with a non-top reading position causes overscroll

### ISSUE THREAD

**Issue by slice** [DagAgren/toot#191]
When opening the app with a reading position that isn't at the very top, tapping the `UIBarButtonItem`s on the toolbar cause the scroll view to scroll too much.

Reproduction video: https://streamable.com/wiiko

Reproduction steps:

- Set a reading position by viewing a toot down your timeline.
- Kill the app and launch it.
- Tap the "Home" toolbar icon to scroll to top.

A similar thing happens to the federated timeline view: it doesn't scroll all the way to the top.

**Comment by DagAgren** [comment]
Think this is fixed now.
