### ISSUE TITLE
Opening a gopher link crashes the app

### ISSUE THREAD

**Issue by dotemacs** [DagAgren/toot#192]
See this toot:
https://mastodon.xyz/@mindshoot/100811451080423629

Click on the gopher link in the above toot crashes the app.

Gopher might be fringe, but so is Mastodon. Please don't just ignore it or block it. 

Thanks

**Comment by DagAgren** [comment]
Fixed, but what happens now is nothing, unless you have a client installed.

**Comment by dotemacs** [comment]
With [this client](https://itunes.apple.com/us/app/gopher-client/id1235310088?mt=8) it should open it smoothly. 

Thank you for taking care of this!
