### ISSUE TITLE
Icons for Toot actions

### ISSUE THREAD

**Issue by Xjs** [DagAgren/toot#194]
Seems like this issue doesn't exist. I'd appreciate icons (reply arrow, recycle arrows for boost, star for fav) under each toot, instead of the text buttons. I don't know if you consider text buttons an USP for the app, if so, I'd be happy for this to be a configurable option :)

**Comment by DagAgren** [comment]
I don't think this will happen unless there is a complete overhaul of the UI. For now, I am considering text icons more user friendly.
