### ISSUE TITLE
Version gate easter egg

### ISSUE THREAD

**Issue by JonathanGerlach** [DagAgren/toot#197]
Find a toot with favorites.  Scroll to bottom of list.  Over scroll and see the glitch which looks like stacked pieces of paper.  Keep scrolling will result in a crash.

**Comment by DagAgren** [comment]
Overscroll on a list of accounts triggers an easter egg game. Do you have a very old device?

**Comment by JonathanGerlach** [comment]
iPhone SE, iOS 12

-Jon

**Comment by JonathanGerlach** [comment]
I can no longer reproduce this crash. I had an iPhone 6 a few days ago and saw this crash repeatedly.  Hope this helps.

-Jon

**Comment by DagAgren** [comment]
Yeah, it doesn't work great on old devices. I would version gate it but I don't know what versions so it will stay for now.

**Comment by narFnarF** [comment]
I have an iphone 5s, running iOS 12 and the minigame (3d balls) worked without any issues. The framerate was stable.
