### ISSUE TITLE
Toots that contain empty lines aren’t expanded correctly when they have a CW

### ISSUE THREAD

**Issue by madrobby** [DagAgren/toot#199]
The toot text is cut off after the first line break and the rest of the toot is not viable. Oddly, sometimes hashtags that are in the rest of the toot body are visible.

**Comment by DagAgren** [comment]
Do you have an example link?

**Comment by madrobby** [comment]
Yes, https://mastodon.social/@thomasfuchs/100893728806232631

This only happens when the toot is expanded in notifications, not when it is shown directly 

![ba2402c4-84f6-4c1a-b9de-f061d9eef81f](https://user-images.githubusercontent.com/3390/46918569-8736cd00-cfa1-11e8-8670-44e3f952d295.png)
![c541b641-7cbc-45c1-bbed-46e3669faed4](https://user-images.githubusercontent.com/3390/46918570-8736cd00-cfa1-11e8-80bf-05fb7299a192.png)
![cb9730a8-c6cd-491f-9f04-cef82becdb75](https://user-images.githubusercontent.com/3390/46918571-8736cd00-cfa1-11e8-8a92-409b4e087021.png)

**Comment by madrobby** [comment]
And sorry about the bad joke

**Comment by DagAgren** [comment]
That is not Toot!.

**Comment by madrobby** [comment]
Whoa, sorry. Confused the clients. 😬🤐
