### ISSUE TITLE
Delay on opening links -> lots of views pop up

### ISSUE THREAD

**Issue by fluffy-critter** [DagAgren/toot#205]
So this is a bit of a weird one but I was viewing this toot: https://social.wxcafe.net/@amphetamine/100951684944722683

I tapped on the link and nothing happened. I thought maybe I just missed the tiny click target so I tapped about ten more times.

Several seconds later I got many views of the linked-to toot layered on top of each other, opening with the same approximate rhythm as my original tapping.

**Comment by DagAgren** [comment]
The delay is because the toot is fetched from the remote instances to your local instance, then displayed in Toot! instead of opened in a browser. Showing a better indication that things are going on is https://github.com/DagAgren/toot/issues/34.
