### ISSUE TITLE
View other instances public timeline

### ISSUE THREAD

**Issue by DennisBankmann** [DagAgren/toot#206]
My favorite missing feature for this already great app is the ability to view remote public timelines. This will be a useful feature for everyone on small/private instances with a quiet federated timeline I believe. It would make remote following requests much easier.
Mast and tootdon have this feature, in my view tootdon implements it a bit better

**Comment by DagAgren** [comment]
I'm not sure how you haven't noticed that this feature exists, as it is the first thing you land on?
