### ISSUE TITLE
Bug: New post appears with another user's name

### ISSUE THREAD

**Issue by ljcooke** [DagAgren/toot#209]
After posting an image, the post appeared in the timeline with the display name of another user, and my username, like:

`Someone Else  @myname`

The avatar was correct. The display name was the same as a post I had boosted earlier.

**Comment by DagAgren** [comment]
Can you reproduce this?

**Comment by ljcooke** [comment]
I haven't been able to reproduce it again.

**Comment by georgehrke** [comment]
I also stumbled over this bug, I don't have THE three reproduction steps,
but I've only seen it in the context of loading in multiple batches. 

I haven't checked Toot all day, load the first batch, scroll up, load the next batch and this batch sometimes contains wrong names. If i recall correctly it's even the name of the next person, so this might be a simple Offset by One error?

I've also seen that it prepends already read toots to the top of the timeline again. That might be related.

**Comment by DagAgren** [comment]
I've seen this happen now, but I can't reliably reproduce it.

However, I took a guess at what might cause it, and tried fixing that, so it might be fixed now.
