### ISSUE TITLE
Add ••• to Toots on Timeline

### ISSUE THREAD

**Issue by VioletPixel** [DagAgren/toot#211]
In order to access the More... menu you currently need to go to a toot's detail view, as the option is missing on timeline views. This is at least inconvinient, and at worse a hassle if the detail view isn't easy to access (i.e. single line toots where the entire text is a link).

**Comment by DagAgren** [comment]
The options in that menu are meant to be accessed seldom enough that it is not worth adding visual clutter to have them on the timeline.
