### ISSUE TITLE
Add Option to for Reply/Boost/Fav Icons Instead of Words

### ISSUE THREAD

**Issue by VioletPixel** [DagAgren/toot#212]
When I'm looking at Mastodon I want the primary focus to be the toots. The words instead of icons distract from the words in the toots and require extra mental effort to ignore as I read my timeline.

Icons would also provide a simpler, cleaner appearance and improve accessibility.

**Comment by DagAgren** [comment]
I disagree on the accessibility. I find icons are far less accessible, which is why I've intentionally avoided them in this design.
