### ISSUE TITLE
"Show more" loses scroll position

### ISSUE THREAD

**Issue by dermike** [DagAgren/toot#214]
I've wished for this before in #100 which was closed with reference to #54.
Now that I run Mastodon 2.6 on my instance it still doesn't work as I was trying to explain in the original issue.
When tapping "show more" I would love it if the new content is loaded above the "show more" button without messing up the timeline. Now I have to scroll down every time "show more" i loaded to try and find the status I was last at. 

Before tapping "show more" with Mastodon 2.6:
![img_5176](https://user-images.githubusercontent.com/4582134/47877030-2ae60100-de1b-11e8-9645-205a1b0a5371.PNG)

After tapping it my scroll position is lost and I have to manually scroll down to find the status by dozens where I was last at:
![img_5177](https://user-images.githubusercontent.com/4582134/47877083-51a43780-de1b-11e8-9c8a-ef68973bb9f2.PNG)

**Comment by DagAgren** [comment]
Do you have the latest version of the app? It's not showing the UI that would normally be shown on 2.6.0.

**Comment by dermike** [comment]
After a restart it looked a bit different with arrows down and worked, but just trying it again the scroll position was lost when loading more. The load more-thingie was not fully visible though (25% out of view on top), could that have something to do with it?

**Comment by DagAgren** [comment]
Could be. That is a really hard issue to fix and should generally not happen in regular use so probably not fixing that.
