### ISSUE TITLE
Pleroma signups fail with cryptic error

### ISSUE THREAD

**Issue by slice** [DagAgren/toot#220]
I'm getting this error when I try to sign in into my Pleroma instance:

![fszx5d8rqj nwwiaibyy2g_thumb_5f1](https://user-images.githubusercontent.com/4206232/48046366-0d7da380-e149-11e8-9292-e79471d6b372.jpg)

It seems to be interpreting the redirect from Pleroma as a cancellation.

**Comment by DagAgren** [comment]
I thought this had been fixed in the latest Pleroma versions? Either way, I am not really supporting Pleroma specifically, so it is up to them to stay compatible.

**Comment by slice** [comment]
Ah, ok. :+1: Hope this gets fixed on their side then.

**Comment by kaniini** [comment]
most likely it is a problem with toot expecting us to reflect the scopes it requests explicitly back to them, when in reality, we grant all possible scopes.  unfortunately, toot being closed source, i am unable to verify this theory.

**Comment by DagAgren** [comment]
I don't check the scopes, but I do parse the response and it probably needs the same fields as Mastodon has.

**Comment by DagAgren** [comment]
Also, if you want access to the code for testing, that can be arranged.

**Comment by JanJastrow** [comment]
Hi,
as I experienced the same problem, I kinda found the solution to this:
Tapping "Authorize" in the OAuth view does not work, but if you **instead tap "Go" on the iOS keyboard**, the login is successful.
Don't know why this is the case, but it worked.
