### ISSUE TITLE
Location of CW text?

### ISSUE THREAD

**Issue by bezthomas** [DagAgren/toot#222]
CW text appears at the top of a toot. When scrolling chronologically, this means you encounter the CW for a large image after seeing it exists, breaking the flow of scanning through the timeline.  

Do any of the following seem practical?
* CW always at bottom
* CW at top and bottom for large images
* CW shifts to top or bottom depending on scroll direction

**Comment by DagAgren** [comment]
Hmm... Shifting is probably the most usable option, but it also would be really distracting. So not quite sure.

**Comment by DagAgren** [comment]
I think realistically speaking this won't be changed any time soon.
