### ISSUE TITLE
Translate toot action

### ISSUE THREAD

**Issue by lamnatos** [DagAgren/toot#223]
As per title, it'd be very nice to have a means to translate toots. It would allow for much more interesting and varied mingling in the fediverse.

**Comment by lamnatos** [comment]
(Oops, I meant to write a description but pressing Enter in the title directly created the issue, sorry about that)

As per title, it'd be very nice to have a means to translate toots. It would allow for much more interesting and varied mingling in the fediverse.

**Comment by DagAgren** [comment]
Hmm. I'm not sure if there is a reasonably well-functioning service that can be used without paying quite a lot for it.

**Comment by lamnatos** [comment]
Mast & Amaroq have toot translation, do we know what service they're using and at what cost?

**Comment by DagAgren** [comment]
Mast uses the Google Translate API and pays for it, it seems.

Not sure how I feel about that, especially since it is Google who isn't exactly the most trustworthy entity.

But also, Google is almost the only viable option in terms of accuracy.

**Comment by lamnatos** [comment]
I've seen [Yandex](https://translate.yandex.com/) and [DeepL](https://www.deepl.com/translator) mentioned. 

**Yandex** looks a lot like Google Translate, a quick test between Greek ↔ English returns OK results, and an [API key requires a paid account](https://translate.yandex.com/developers). It looks like you can use it like Amaroq does though, by loading the translation result page directly.

**DeepL** is much more limited in number of languages and also provides a paid tier.

**Comment by DagAgren** [comment]
Don't think I really feel like paying money to Google for this, and I don't think any of the other options are really good enough.
