### ISSUE TITLE
I cannot Enable Notification on toot.veer66.rocks

### ISSUE THREAD

**Issue by veer66** [DagAgren/toot#226]
I cannot enable notification on toot.veer66.rocks, which is a Pleroma instance. I got an error message that the server return 404. 

Which URL should I check? Does it has to be websocket?
![a5375c7e-66f5-46a9-a77b-630a94bca14e](https://user-images.githubusercontent.com/370688/48294899-00024980-e4ba-11e8-9115-f97ff51ba5db.png)

**Comment by DagAgren** [comment]
Pleroma has not implemented push notifications, so it will not work.
