### ISSUE TITLE
My home timelines do not refresh.

### ISSUE THREAD

**Issue by veer66** [DagAgren/toot#227]
My home timelines do not refresh both on toot.veer66.rocks and kpop social. I try to swipe my timeline down but it didn’t work. 
![10e4525a-9886-4fb7-9ebc-699819a75bcc](https://user-images.githubusercontent.com/370688/48294981-959dd900-e4ba-11e8-8aa0-53d201e3edc3.png)

![85630142-1a93-4cbf-86a7-01be214955f7](https://user-images.githubusercontent.com/370688/48295093-41dfbf80-e4bb-11e8-8777-120a884c05d4.png)

**Comment by DagAgren** [comment]
https://github.com/DagAgren/toot/issues/25 is the issue for fixing this problem.
