### ISSUE TITLE
Push notifications no longer working after updating server version

### ISSUE THREAD

**Issue by vy-let** [DagAgren/toot#228]
I recently upgraded my mastodon server version to 2.6.1, and for whatever reason Toot stopped receiving push notifications. I assume the reason for that is on my end. However, when I go into Toot’s settings, and attempt to disable and re-enable notifications, I get a 400 error mesage (see screenshot), and I can’t figure out another way to “refresh” the connection. The only other user on my instance is getting push OK, and is able to toggle notifications just fine. When I go to the notifications tab and pull to refresh, they come in OK too. 

![5dc98979-4636-42c2-8b7b-8c6ea38e63b4](https://user-images.githubusercontent.com/2660568/48308201-0fb27a00-e51c-11e8-8f0d-2c1776b9c886.png)

I’m using v1.1 (50).

**Comment by DagAgren** [comment]
Are you using Pleroma? It does not support push notifications.

**Comment by vy-let** [comment]
I'm using stock Mastodon version 2.6.1

**Comment by DagAgren** [comment]
That is very weird... maybe try logging out and in again?

**Comment by vy-let** [comment]
Logging out and in worked. Not an ideal flow, but my issue is fixed, so if it's not a widespread problem… 🤷🏻‍♀️

**Comment by DagAgren** [comment]
Really not sure why it was 404'ing, though. Very mysterious. I'll close this for now and see if it pops up again...
