### ISSUE TITLE
Failed to understand notification

### ISSUE THREAD

**Issue by cmantsch** [DagAgren/toot#230]
I got several notifications with following text:

The operation couldn’t be completed.
(NotificationService.DecryptptNotificationErrorType error 1.)

**Comment by cmantsch** [comment]
![581d7791-98f3-4b38-9ded-111fd4eb3075](https://user-images.githubusercontent.com/16846537/48407764-deae9100-e737-11e8-8570-efe26f0c8e82.jpeg)

**Comment by DagAgren** [comment]
You probably need to log out and in again.

**Comment by DagAgren** [comment]
Very weird... It is a bug, probably, but notifications are notoriously difficult to debug since they run in an extension that can't easily be debugged or logged.

I'll try to make the error message a tiny bit more descriptive, and let's wait and see if it happens again. Closing until then.
