### ISSUE TITLE
Toots repeating after „show more“

### ISSUE THREAD

**Issue by fihu** [DagAgren/toot#231]
Seems like sometimes the most recent toots already loaded at startup (toots X) are loaded another time, when the user does several „show more“ operations (from the last read toot upwards, toots U).
So the last read toots are U, then there’s „show more“, then toots X (new, up till now).
Several times „show more“ will load toots V, toots W and then toots X which then are followed by the first toots X.
Is this understandable?

**Comment by DagAgren** [comment]
What server are you using?

**Comment by fihu** [comment]
Norden.social, running Mastodon 2.6.1

**Comment by chucker** [comment]
I’ve experienced this a few times on mastodon.social.

**Comment by thegcat** [comment]
Just pipping in to confirm that I have observed similar behaviour. The steps seem to be "multiple load more" but I haven't paid much attention when it happened.

**Comment by thegcat** [comment]
Ah, this is on toot.kif.rocks, currently running 2.6.1.

**Comment by VirtualWolf** [comment]
I saw it just now on mastodon.social, it's currently on 2.6.4.

**Comment by lamnatos** [comment]
I've just realized that the duplication only happens when moving upwards in the time line i.e. when loading newer items. It has never happened to me when moving downwards in the time line, from newer to older items. 

Maybe this might help a little in the investigation of the issue.

**Comment by DagAgren** [comment]
I *think* I've fixed this now. I never reproduced it, but I have now re-written all the timeline handling to be more robust and testable and predictable, so hopefully I got rid of this bug in the process.
