### ISSUE TITLE
Error while loading: The data couldn't be read because it isn't the correct format. (Cannot initialize Type from invalid String value audio).

### ISSUE THREAD

**Issue by veer66** [DagAgren/toot#232]
I use Pleroma (2018-11-17).

![default](https://user-images.githubusercontent.com/370688/48676074-21d38e80-eb94-11e8-90b3-97a8bf1d61bb.png)

**Comment by DagAgren** [comment]
Sounds like Pleroma has added a new attachment type that is not supported.
