### ISSUE TITLE
"Enable notifications" button shows regardless of if instance supports it

### ISSUE THREAD

**Issue by mistydemeo** [DagAgren/toot#234]
In the user's settings for a particular instance, the "enable notifications" button is shown unconditionally if notifications are off. However, the API used by it was added in Mastodon 2.4.0: https://github.com/tootsuite/mastodon/commit/97e43ec5f08aeafe0cb34a2e71e857f22c547f7a As a result, Toot will always display a 422 error for those instances.

Since Toot knows what an instance's version is, it should probably avoid hitting this route when the server is running 2.3.0 or older.

**Comment by DagAgren** [comment]
I'm generally not putting in much effort to support old Mastodon versions. Instance operators should be keeping their installs up to date. It is risky not to, and I don't want to enable that.
