### ISSUE TITLE
Profile glitch in portrait mode

### ISSUE THREAD

**Issue by SHSunny** [DagAgren/toot#240]
![133b204c-c540-49e9-9b7f-26abf6327fa0](https://user-images.githubusercontent.com/45603634/49459636-c6d6a400-f7ef-11e8-9b7f-a9e2999a3897.png)
![108f5b45-43fc-4391-86cc-41ce56f058d0](https://user-images.githubusercontent.com/45603634/49459637-c6d6a400-f7ef-11e8-873b-2ee05c38cadc.png)

This glitch completely messes up the info when lookig at my profile and my profile only. It doesn’t happen for any other profile on the app.

**Comment by DagAgren** [comment]
Looks like you have some very long titles in your metadata, and the app tries to avoid breaking them.

I should probably put in some limit so that they never get wider than half the screen or so.

**Comment by SHSunny** [comment]
Reducing the particularly lenghty one seems to have fixed the issue. Thanks! Hope it helps improve the app
