### ISSUE TITLE
Pull to refresh doesn't take you to the top of the newly refreshed list.

### ISSUE THREAD

**Issue by dar-irl** [DagAgren/toot#242]
After you pull to refresh the list of toots, you need to tap 'home' or the instance switcher to take you to the top of the list.

**Comment by DagAgren** [comment]
This is by design.

**Comment by dar-irl** [comment]
Can this be an optional enhancement? Refreshing and then having to scroll upwards doesn't make much sense usability-wise.

**Comment by DagAgren** [comment]
Most people prefer this behaviour, as it lets you keep your place in the timeline. I don't think it warrants cluttering up the settings further.
