### ISSUE TITLE
"Error while loading" in Notifications column

### ISSUE THREAD

**Issue by jumoru** [DagAgren/toot#243]
I'm currently unable to update the Notifications column. Every time I do a pull to refresh I get the following error message: "Error while loading - Pull to down to retry"

I've already tried removing & re-adding my account as well as reinstalling the app from the App Store, but it didn't help

Push notifications are working however

Toot! version 1.1
iOS 12.1 and 12.1.1

![img_3305](https://user-images.githubusercontent.com/27491477/49588827-0b854b00-f968-11e8-9533-4dd2891a702a.jpg)

**Comment by DagAgren** [comment]
I've tried adding a bit more defensiveness to 1.2. Try again once it's out!
