### ISSUE TITLE
Swipe a toot left/right to [action]

### ISSUE THREAD

**Issue by fihu** [DagAgren/toot#245]
Similar to Tweetbot/Mail.app, add swipe actions to a single timeline entry (toot).

E.g:
Swipe right -> Fav toot
Swipe left -> Open toot
3D-Touch + Up -> Normal iOS behavior for 3D + Up is "Peek and open", so this should be Reply (although the swipe motion would fit to Boost :/)

**Comment by DagAgren** [comment]
This seems like it would be annoying if triggered by mistake. I use it in the follow requests view, and it makes it feel very unsteady, so I doubt I will do this.
