### ISSUE TITLE
Graphical glitch with thread indicators

### ISSUE THREAD

**Issue by kode54** [DagAgren/toot#250]
There appears to be an issue with thread indicators and avatars, possibly only exposed when a post has been CWed. After expanding the CW open, the thread indicators appear to Z-fight with the avatar, flickering with the screen refresh rate. I can try to supply a screen recording, but it will contain a CWed image, which I need to check if it contains NSFW material before I post it.

Running on a 2018 budget series iPad.

**Comment by DagAgren** [comment]
I can't reproduce this.
