### ISSUE TITLE
Doubleclick to boost

### ISSUE THREAD

**Issue by DagAgren** [DagAgren/toot#26]
Add an option to settings to require two clicks on the "BOOST" button in order to boost.

First click might just make the button bounce to a bigger size?

cc @Gargron

**Comment by zigg** [comment]
I'm a fan of the workflow where there's a(n optional) confirmation dialog instead of a double-tap.

**Comment by Gargron** [comment]
Why not the slide/long-slide left/right mechanic?

**Comment by DagAgren** [comment]
It's a lot of work to implement a view for it, so I was going for a simple solution for now.

**Comment by DagAgren** [comment]
Made a simple double tapping version for now. I will consider a nicer UI in the future, but for now I'm just getting it done.
