### ISSUE TITLE
“show more” doesn’t offer post loading directionality on Pleroma instances

### ISSUE THREAD

**Issue by dar-irl** [DagAgren/toot#261]
The “Show More” button doesn’t provide the directional arrows on Pleroma servers that it does on Mastodon servers — is this a Pleroma or Toot issue? It seems like they only load below the button regardless of which way you scroll.
![c801f1f7-dc6b-4b4a-bf7f-1d940953d06e](https://user-images.githubusercontent.com/18043024/50746499-5d3a2300-11fd-11e9-8b8b-28c30afd0fa6.png)

**Comment by DagAgren** [comment]
That feature depends on a new API that only the latest versions of Mastodon supports, and Toot! checks the version field of the instance to see if it is available.

If Pleroma has implemented it, or will, then I'll need to know how to detect the version that does support it to add support for it.

(The API in question is the `min_id` parameter on timeline queries.)

**Comment by DagAgren** [comment]
If Pleroma does implement it, make a new issue to add support for it!
