### ISSUE TITLE
Option to add media to toots from files.app

### ISSUE THREAD

**Issue by tychoquad** [DagAgren/toot#268]
Right now, if you want to toot an image or video, it has to be in your camera roll. I would like the ability to toot things from files.app, Dropbox (and most likely in iOS 13, external storage) and so on.

I would also like the ability to paste content into toots, but I’m pretty sure that’s a different issue.

**Comment by DagAgren** [comment]
Is a sharing extension good enough?

**Comment by tychoquad** [comment]
A sharing extension would be great, I keep Mast around at the moment just so I can toot news articles from it.

I’m not exactly sure, but I’m under the impression that you will be able to paste images/.gifs in the next build to allow .gif keyboards to work? Will this allow drag and drop of media on the iPad? I’d be happy with that 😊

**Comment by DagAgren** [comment]
Sharing extension issue is https://github.com/DagAgren/toot/issues/97.

Paste will work in the next version, but not sure about how iPad drag and drop works at all, have not looked into it.
