### ISSUE TITLE
Feature-Request: adjust loading screen to dark theme

### ISSUE THREAD

**Issue by yuki-93** [DagAgren/toot#281]
Hey, 

as we discussed on Mastodon [1], see linked thread, it would be nice to adjust the loading screen to dark theme. This is the screen when you send a toot, with the mastdon mammoth and the music notes. 

This screen is always a light gray hazard covering the screen. This is okay for the light themes but is very exhausting for the eyes in dark themes (obsidian and mastodon). So it would be very nice, to have this also adjusted into dark mode. 

[1]: https://chaos.social/@yuki/101503883582055909

**Comment by DagAgren** [comment]
I solved this the most efficient way, which is by: Completely redesigning and re-implementing the whole thing.
