### ISSUE TITLE
Encrypted database

### ISSUE THREAD

**Issue by JonathanGerlach** [DagAgren/toot#284]
By default, the database of toots should be encrypted so that users are safe from nefarious companies and governments.

**Comment by DagAgren** [comment]
Not sure what your attack scenario here is. iOS will apply quite a lot of protection to app files by default, and I am not sure in what scenario you could get through that and access cache files from outside the app.

Also, handling cryptography yourself is difficult and fraught with pitfalls, and introduces a lot more possibilities for bugs and problems, so unless there is some realistic attack vector here, I'd rather not touch this.
