### ISSUE TITLE
Image upload option disappears if image is removed from toot

### ISSUE THREAD

**Issue by fluffy-critter** [DagAgren/toot#286]
1. Start a toot with “library”
2. Select a photo
3. Realize it needs to be cropped better to remove PII and edit the photo in the Photos app
4. Return to Toot
5. See the image is in a weird superpositional state and remove it from the toot
6. Have to completely re-draft toot because the image upload widget is gone

**Comment by fluffy-critter** [comment]
Nope, all image related functions totally disappeared.

**Comment by DagAgren** [comment]
The bar above the keyboard should always be there, though, it never disappears? The buttons under the text box do disappear, but that one shouldn't.

**Comment by fluffy-critter** [comment]
The keyboard bar disappeared. I had no way of adding another image. Let me see if I can reproduce and I’ll take a screenshot if so.

**Comment by fluffy-critter** [comment]
Ah I figured out what happened - the “add image” buttons are still there but my keyboard was gone because I wasn’t in a text field. It seems weird to tie adding an image to having the text field selected. So this is less a bug and more a UX problem. :)

**Comment by fluffy-critter** [comment]
Couldn’t figure out how to attach an image on the github mobile interface, apologies for email cruft 

--

**Comment by DagAgren** [comment]
Oh yeah. It's not brilliant, but it kind of has to be that way, since you can have multiple toots on the posting screen. I don't really have a better solution for it.

**Comment by fluffy-critter** [comment]
Could the +library +camera buttons be attached to the image attachment editing UI (which would remain in place but simply be blank if there's no attachment)?
