### ISSUE TITLE
[Request] preload full quality images when tapping on one

### ISSUE THREAD

**Issue by tychoquad** [DagAgren/toot#287]
When tapping on an image preview in a toot with 2 or more, you have to wait for each image to load completely from scratch when swiping between them. Could you make it so if I tap and load the full image in a toot, could you load the other possibly 3 images as well so I can seamlessly swipe between them?

**Comment by DagAgren** [comment]
Not sure about this. It's a bit rude to the servers to load large amounts of data you may not actually want.

**Comment by tychoquad** [comment]
That’s a fair concern, what if instead of loading all 4 images, it only loads the ones that you would see if you swiped left/right of the one you tapped on, then load more as you swipe?

So, if you tapped on image 1, it would load images 1 and 2. Swiping to image 2 would load image 3 and swiping to image 3 would load 4.

This should greatly reduce the load on the server while still providing a more seamless experience for the user, as long as they are looking at the images for more than 1 second anyway.

**Comment by DagAgren** [comment]
That might be a better solution.

**Comment by VirtualWolf** [comment]
What about showing the same lower-resolution preview that you get for the first image, for all of them when you first swipe? My main frustration is seeing all the thumbnails in the timeline, tapping on one, then swiping to the next and get a completely black screen while the image loads, instead of getting the lower-resolution thumbnail like I just had for the first image.

**Comment by DagAgren** [comment]
Hmm, I guess it would be worth at least checking to see if that thumbnail happens to be in the cache and using it in that case, since it probably will be.

**Comment by VirtualWolf** [comment]
Yeah, FWIW I don't ever tap on images until at least the thumbnails have loaded anyway so I'd imagine it'd _always_ be there in that particular case.
