### ISSUE TITLE
@-mention autocompletion in the share extension

### ISSUE THREAD

**Issue by timonus** [DagAgren/toot#291]
Following up from [this Toot](https://mastodon.social/@tootapp/101668626290746669):

The share extension introduced in 1.5 is quite fully featured, but it lacks @-mention autocompletion. Given that remembering which instance a given user is on can be challenging, autocompletion seems important enough to consider adding.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DagAgren** [comment]
It actually has it and it is working perfectly.

It's just, uh, invisible.
