### ISSUE TITLE
Return inserts extra newlines

### ISSUE THREAD

**Issue by tewha** [DagAgren/toot#293]
When typing, return seems to enter multiple newlines. Here, I typed "A\<return\>B." I then had to backspace 3 times to get back to A.

![file 2019-03-02 2 12 36 pm](https://user-images.githubusercontent.com/108106/53688210-4e4f8880-3cf5-11e9-8d7b-ac4ac220e363.jpeg)

It occurs to me that this might be intentional; if so, please add a way to turn it off. It's not a bad idea, but considering no other app does it I'm going to hit return twice anyway and end up with four newlines. :)

**Comment by DagAgren** [comment]
There is already a way in the settings.
