### ISSUE TITLE
Support polls

### ISSUE THREAD

**Issue by singingwolfboy** [DagAgren/toot#295]
Polls were recently merged in Mastodon: https://github.com/tootsuite/mastodon/pull/10111 Can Toot support viewing them and interacting with them?

**Comment by DagAgren** [comment]
Probably yes.

**Comment by CaptainPotassium** [comment]
I would *love* that!

**Comment by tychoquad** [comment]
Until you get a chance to implement polls, I don’t suppose you could add a link/indicator to toots with polls so that we know that a toot has one?
