### ISSUE TITLE
Obsidian theme: CW input hard to read, #221 does not apply

### ISSUE THREAD

**Issue by cpsdqs** [DagAgren/toot#296]
Text input into the CW text field is hard to read with either dark theme. Also (less importantly) #221 does not seem to apply to the Obsidian theme.

<img alt="Screenshot of the compose screen on an iPhone with the Obsidian theme. The text in the CW input is hard to read. Also, the keyboard is not dark" title="Screenshot of the compose screen on an iPhone with the Obsidian theme. The text in the CW input is hard to read. Also, the keyboard is not dark" src="https://user-images.githubusercontent.com/5412095/54049731-9ed75200-41dd-11e9-87d5-b8f2315f7f13.png" width="375" />

(version 1.5.1 (69) on iOS 12.1.4)

**Comment by DagAgren** [comment]
I've seen a similar report before, but I can't reproduce this at all.

**Comment by cpsdqs** [comment]
Seems to be fixed in 1.6
