### ISSUE TITLE
Multiple taps on toot can produce multiple detail view pushes

### ISSUE THREAD

**Issue by bjoreman** [DagAgren/toot#297]
Usually, tapping a toot pushes a detail view from the right. Sometimes, not sure when or why, there's a delay before the view is pushed, I'm guessing because something is being loaded. My usual reaction is to think my tap failed to register (or that I mis-tapped) and tap again. Once the app catches up, I will get one detail view pushed for each tap, which also means I have to back out through all of them to get back to the timeline where I started.

**Comment by DagAgren** [comment]
I think this basically falls under https://github.com/DagAgren/toot/issues/34.

**Comment by WinterMagik** [comment]
sorry to post in this thread but i'm new and don't know how to make a totally new one :\

I just bought this app for iphone and it just freezes when it tries to launch.

IOS 10 iphone 5. 

Any help would be great as i've paid 5 bucks for it and i'm looking forward to using it :)

**Comment by DagAgren** [comment]
There is a "New issue" button on the top right. But this sounds like https://github.com/DagAgren/toot/issues/165.
