### ISSUE TITLE
Searching failed. Server throttled your connection (404)

### ISSUE THREAD

**Issue by mrscl** [DagAgren/toot#298]
Search option doesn't give any result on the app. 
''Searching failed. Server throttled your connection (404)''

**Comment by tychoquad** [comment]
I just tried searching on 3 different servers, they all worked fine. What server is it, and can you search on its website?

**Comment by DagAgren** [comment]
Did you search a lot? Because that error message means the server thinks you did and is refusing to do any more. Waiting a little while and trying again should fix it.
