### ISSUE TITLE
Crash while viewing some user profiles

### ISSUE THREAD

**Issue by vy-let** [DagAgren/toot#300]
I'm seeing an issue when viewing certain people's profiles where, when I start scrolling down, before I get past their pinned toots, the app hangs. One such user I'm seeing this with is [@lynnesbian](https://fedi.lynnesbian.space/@lynnesbian). I'm not sure how to replicate it on other accounts or devices, but it *is* 100% replicable for these certain users on my device.

Right when the app hangs, a placeholder toot scrolls into view (see screenshot). The scroll view halts, and the app stops responding to any input. If I keep trying to scroll, it will occasionally jump down a couple times, before crashing.

I don't feel it's terribly urgent that I be able to view these profiles on my end---in fact, I've been seeing this for a few months. I'm more interested in getting to the root of the issue.

![Placeholder Toot Crash](https://user-images.githubusercontent.com/2660568/54652363-4117f500-4a7c-11e9-86bc-bd53da33ed47.png)

**Comment by DagAgren** [comment]
I can't seem to reproduce it. Have you tried deleting the app and reinstalling?

**Comment by DagAgren** [comment]
Anything new on this?

**Comment by vy-let** [comment]
Sorry, I've been a bit too busy to investigate. However, the latest version of the app has fixed this issue, with no re-install necessary.
