### ISSUE TITLE
Enhancement: Attachment thumbnail type overlay

### ISSUE THREAD

**Issue by lamnatos** [DagAgren/toot#301]
Some attachments are static images, some are silent gifs and some are videos with audio. You cannot tell which is which from the thumbnail shown, in the timeline nor in the toot's details (I think).

I think it'd be useful to add a small overlay on the corner of the thumbnail with the type of the attachment. It could even be the extension of the attachment, I think by now most people know the differences between jpeg, gif and mp4.

![toot-img](https://user-images.githubusercontent.com/178458/54682747-a533cb00-4b07-11e9-8933-8174b5911928.png)

![toot-gif](https://user-images.githubusercontent.com/178458/54682755-ac5ad900-4b07-11e9-8af6-ad2227e792ee.png)

![toot-vid](https://user-images.githubusercontent.com/178458/54682768-b11f8d00-4b07-11e9-9fad-f48dae091244.png)

**Comment by DagAgren** [comment]
Not sure about this, I think it would be too visually busy and distracting.

**Comment by tychoquad** [comment]
Since the timeline itself doesn’t show animation, a marker for non-static images would be extremely helpful. I suggest a tiny play arrow in the corner, that should do the job

**Comment by DagAgren** [comment]
That animations are not shown is a the actual problem, which will be fixed.

**Comment by lamnatos** [comment]
@DagAgren Does this mean that the plan is to animate them in the timeline? If so, won't that lead to a potentially visually distracting timeline where things animate left and right?

**Comment by DagAgren** [comment]
I haven’t made any decisions on those things yet, but it’s out of scope for this issue.
