### ISSUE TITLE
Feature Request: UI for filtering API 

### ISSUE THREAD

**Issue by lamnatos** [DagAgren/toot#302]
In addition to the existing ability to permanently mute/block users, I think it'd be really useful to implement a UI for [Mastodon's filtering API](https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#filters).

I'd love to be able to set temporary filters (aka mutes) for tags/words/discussions **I'm not** interested in from people **I am** interested in.

**Comment by DagAgren** [comment]
Unfortunately, that UI is quite complicated and is definitely way too little benefit for too much work for the foreseeable future. I am kind of drowning in more important tasks already, so I will just close this for now.

The web UI can be used for this currently.

**Comment by lamnatos** [comment]
I understand. Would you consider adding a link somewhere in the app linking to the current instance's web UI for setting filters?

**Comment by DagAgren** [comment]
I guess it does seem to be deeplinkable, so maybe that could be fairly easily done.

**Comment by DagAgren** [comment]
Done.
