### ISSUE TITLE
Right-to-left language display names on wrong side of notification text

### ISSUE THREAD

**Issue by alanapost** [DagAgren/toot#307]
![6CE9D4E9-BA08-458C-A39C-16759BF8D9AC](https://user-images.githubusercontent.com/17862/55007157-2d005600-4f9c-11e9-9e77-5922cb865b82.jpeg)

When users write their display names in right-to-left languages (only example is Hebrew; should be confirmed with others?), their display name shows up on the wrong side of the notification’s first line.

**Comment by DagAgren** [comment]
Think I found the right Unicode special characters to make it behave reasonably.
