### ISSUE TITLE
Notification are received twice (doubled)

### ISSUE THREAD

**Issue by narFnarF** [DagAgren/toot#309]
Every time I receive a push notification from Toot, I receive it twice. All notifications from Toot are doubled in my phone's lock screen and notification center. This started about 1 month ago.

I tried:
* logging out of all instances and re-logging in
* uninstalling the app and reinstalling

Screenshot: https://i.imgur.com/8cE2wxU.png

**Comment by DagAgren** [comment]
You probably need to kill an extra login session from the web interface.

**Comment by narFnarF** [comment]
I confirm this fixed my problem. I don't receive double notifications anymore.

In case someone reads this in the future, you need to go in the mastodon website > Settings >Account > Autorised apps.
Direct url: <yourInstanceURL>/oauth/authorized_applications
So, for example, mine is https://idlethumbs.social/oauth/authorized_applications

You'll find multiple instances of "Toot!" in the list. You need to revoke all of them by clicking Cancel. 

Then, fully close Toot on your phone and relaunch it. You'll need to re-loggin into your account. In my case, all my data was kept so i'm happy. :)

**Comment by pLeskovar** [comment]
I want to connect github and heroku but there's signed the error: Item could not be delivered. Can you help me?
