### ISSUE TITLE
The favorited notification text is cut in French

### ISSUE THREAD

**Issue by narFnarF** [DagAgren/toot#310]
When I receive a notification from Toot when a user favorite my posts, the title is not displayed completely in French.

I see: 
"_name of the user_ a ajouté votre po..."
(For reference, this would translate to: "_name of the user_ added your po...")

Screenshot: https://i.imgur.com/1wftzWU.png

**Comment by narFnarF** [comment]
I would suggest finding a wording that put "favorited" to the beginning of the sentence, and the username at the end, in case the name is very long.

For example:
"Favorited by _username_"
(In French: "Favoris de _username_)

It might not be perfect grammer or syntaxt, but at least I would understand that we're talking about favorites.

**Comment by DagAgren** [comment]
Toot has no control over that text, it comes from the server.
