### ISSUE TITLE
Local timeline isn’t showing only server’s toots now

### ISSUE THREAD

**Issue by VirtualWolf** [DagAgren/toot#311]
I think this has started with one of the latest versions, but when I’m viewing my local server’s local timeline (mastodon.art) I’m seeing toots from a whole lot of _other_ servers too, not just mastodon.art like it used to.

It’s occurring on both my iPhone and iPad, both running the latest iOS and Toot 1.7. mastodon.art is currently on 2.7.4.

**Comment by DagAgren** [comment]
It's just that local and federated were accidentally swapped. Fix on the way.
