### ISSUE TITLE
Still no support for viewing GIFs or videos

### ISSUE THREAD

**Issue by CaptainPotassium** [DagAgren/toot#313]
It would be really, really great if Toot! had support to view GIFs and videos right in the timeline. Needing wait for to open Safari everytime I want to watch something is a huge inconvenience. Are there any plans to implement that feature? 

(I apologise if this issue isn't formatted correctly, I'm new to GitHub)

**Comment by tychoquad** [comment]
Apparently it’s under consideration https://github.com/DagAgren/toot/issues/301#issuecomment-475530328

**Comment by CaptainPotassium** [comment]
Do you know why it's taking so long? This seems like an absolutely *crucial* feature that's missing, and yet it's been at least 10 months since this issue was first brought up
