### ISSUE TITLE
Control Center Bug 

### ISSUE THREAD

**Issue by CaptainPotassium** [DagAgren/toot#314]
Approximately 80% of the time I try to swipe up to open Control Center while using the Toot! App it tries compose a new toot from the camera or the media gallery.

A video of the bug in action can be seen here: https://youtu.be/D1EGcSASP0Q

This screen capture was taken on an iPhone 6S Plus running iOS 12.2, and Toot! v1.7.1 (76)

**Comment by DagAgren** [comment]
I think that realistically, I don't have the time to work on redesigning for older phones.
