### ISSUE TITLE
:: in toot content creates blank space

### ISSUE THREAD

**Issue by slice** [DagAgren/toot#315]
For example, typing "Option::map" in a toot looks like:

`Option   map` (but with a wider space)

I assume it's trying to parse it into an emoji.

**Comment by DagAgren** [comment]
Does it work in the web interface?

**Comment by slice** [comment]
Yes. Copying the toot text from the app also returns the correct content.

**Comment by DagAgren** [comment]
Turns out this only happens if you also do not have any other emojos in the toot, which is why I didn't catch it in testing.
