### ISSUE TITLE
Support Keybase Verification

### ISSUE THREAD

**Issue by lucascantor** [DagAgren/toot#316]
Keybase verification was recently implemented in Mastodon, but the Toot! app doesn’t show users’ verified Keybase profiles along with the rest of their profile metadata.

Is this something that could be easily shown in the Toot! app as well?

**Comment by DagAgren** [comment]
Doesn't look like it is exposed in the API, so there is no way to do it at the moment.

**Comment by lucascantor** [comment]
I've opened a [feature request](https://github.com/tootsuite/mastodon/issues/10777) for this in `tootsuite/mastodon`

**Comment by lucascantor** [comment]
@DagAgren FYI - Eugen confirmed the API docs hadn’t been updated but this is supported now 🎉

https://github.com/tootsuite/mastodon/issues/10777#issuecomment-493674254
