### ISSUE TITLE
[Question] Is Toot fully open-source/free-software?

### ISSUE THREAD

**Issue by asddsaz** [DagAgren/toot#319]
> “Talk is cheap. Show me the code.”

― [Linus Torvalds](https://www.goodreads.com/quotes/437173-talk-is-cheap-show-me-the-code)

**Comment by tychoquad** [comment]
No, only the relay notification server is open source. https://github.com/DagAgren/toot-relay

**Comment by DagAgren** [comment]
No, not at the moment. I would like to open it, but the reality of it is that it is highly difficult to sell an app on the app store and keep it open source, due to people cloning and re-uploading it.
