### ISSUE TITLE
When using iOS Sharing Unable to Add Image Text

### ISSUE THREAD

**Issue by GitPuffy** [DagAgren/toot#321]
When using iOS sharing of a photo, when pressing on the image to add a text description of the image or to use crop functions I am returned to my camera roll to select another image. I was careful not to press on the X at the top right of the image. Please adjust the behavior so that when using iOS sharing from my Photos to the Toot! app we are able to add image text. Thank you.

**Comment by DagAgren** [comment]
It's a crash, and it is not easily fixable until Apple fixes some bugs, see https://github.com/DagAgren/toot/issues/292
