### ISSUE TITLE
Possibility to switch sandwich menu and reply button positions

### ISSUE THREAD

**Issue by DysphoricUnicorn** [DagAgren/toot#327]
I would like to be able to switch around the sandwich menu opener and reply button because I’m used to touch the upper right of the screen to copy the direct link to a Toot but now I keep hitting the reply button.

![A6CDA51E-2ED2-40AB-A039-840050ADB81F](https://user-images.githubusercontent.com/7807969/58632533-0c2ee680-82e6-11e9-9bee-5fc0347f07e3.jpeg)

**Comment by DagAgren** [comment]
Unfortunately, I'm fairly convinced this is the correct ordering for them, both visually (it looks really ugly the other way around), and due to the relative importance of the functions. I don't think it's worth a switch.
