### ISSUE TITLE
long pressing actions causes login screen to be shown

### ISSUE THREAD

**Issue by trwnh** [DagAgren/toot#329]
![45096BA8-34F2-4A03-A51A-07F3BF851AC5](https://user-images.githubusercontent.com/10606431/58669214-05619d00-8301-11e9-9f75-0e19b6cb3a6d.jpeg)

i assume this is because of some multi-account logic, but it still shows even when only a single account is logged in (and asks you to log into the already-logged-in instance)

**Comment by DagAgren** [comment]
Should already be fixed?
