### ISSUE TITLE
Make new iPad layout  toggleable

### ISSUE THREAD

**Issue by dg01d** [DagAgren/toot#330]
New iPad layout is far too information dense. I don’t need to have the full width word “Notifications” &c present statically on the screen, it’s just taking up real estate and unnecessarily compressing the *reason* for using an app, the posts of people I follow.

Please consider making a toggle in settings for this? Either to remove the sidebar altogether or to drop it back down to **just** the icons.

**Comment by DagAgren** [comment]
Generally, super-wide columns of text are very hard to read, so I'm not sure it is actually an improvement in readability to have them stretch all the way across the screen?

**Comment by dg01d** [comment]
While its true that super-wide all across the screen can be hard to read, I'd say that a column with sufficient whitespace, where the **content** is in the centre of the screen, is far easier to read than the present toot! layout, where there's a static column of non-informative text taking up c.45% of the screen, with the **content** restricted to less than half the screen (after the leading edge for avatars)

The present iPad layout just feels restrictive in how it forces all interaction into one small corner of the screen. Take a look at Twitteriffic and (best case) Tweetbot - the **content** is central and dominates the screen presentation; they use different methods of presentation of optional items, but both ensure that the primary interaction area is the dominant aspect of the screen estate.

![Tweetbot](https://user-images.githubusercontent.com/1061809/58692987-b3b02580-8387-11e9-9a08-4175b6fba8ab.jpg)

![Twitteriffic](https://user-images.githubusercontent.com/1061809/58693022-c3c80500-8387-11e9-8de7-ef0996459083.png)

**Comment by DagAgren** [comment]
The bar can't be easily collapsed to icons, as it contains named lists and pinned hashtags.

I also absolutely hate the modern trend of mystery-squiggle buttons that make you guess what they do.

**Comment by dg01d** [comment]
But the bar is **so wide**

40% of the screen estate is a lot. If it could be toggled, even toggled to well-established iconography (home, world, &c) then it wouldn’t take up so much

**Comment by DagAgren** [comment]
I could look into if it can be shrunk a bit on smaller screens.

But as I said, it has custom content in so it can't easily be shrunk to icons.

**Comment by DagAgren** [comment]
All right, I tried turning the width of it down a bit. Let's see how that works, and continue the discussion after the next release if it still seems necessary.
