### ISSUE TITLE
Feature request - local and federated feeds

### ISSUE THREAD

**Issue by michbarsinai** [DagAgren/toot#332]
Unclear how to switch between them, even though #3 and #24 are closed. 

iPhone 6s

**Comment by DagAgren** [comment]
Bottom right button, and tapping the navigation bar title.

**Comment by jaredmoody** [comment]
This UI really needs to be improved, For over a year I just thought Toot! had no way to view local/federated until I tapped it by accident, then googled my way here for how I did it. 

This kept me from recommending Toot! to others, and still does - I have to tell any friends, yeah, it makes no sense, but tap that account switcher wheel thing to view local, *then* the top middle to get to federated.

IMO making the drop down in the middle the place where you switch between feed/local/federated would be a massive improvement- that’s one of many places I looked for how to do this.
