### ISSUE TITLE
Images from Share Sheet aren’t always included in toots

### ISSUE THREAD

**Issue by daprice** [DagAgren/toot#334]
I’ve run into this when trying to share screenshots and photos from ARKit sessions. Photos shared directly from the Photos app seem to work ok.

Steps to reproduce in Toot! 1.8.2 on iOS 12.3.1:
1. Take a screenshot in any app or the home screen, or take a photo in an AR Quick Look session
2. Tap the screenshot preview to bring up iOS’s screenshot editor
3. Tap Share within the screenshot editor and choose Toot! as the sharing target

Expected result: the toot composer includes the image being shared.

Actual result: the toot composer does not show any image, but I send it anyway assuming the image will be attached, then feel like an idiot when I realize I’ve just sent an image-less toot.

**Comment by Frederick888** [comment]
I can confirm this behaviour with v1.9.1 (88) running under iOS 12.1.1.

And the behaviour seems to be consistent here in my case, i.e. the image is *never* included instead of "aren't always".
