### ISSUE TITLE
[ios13] show more never loads upwards

### ISSUE THREAD

**Issue by tychoquad** [DagAgren/toot#337]
Under iOS 13, the load more function is broken slightly. If you position the arrows to load content upwards, it doesn’t appear to hold the scroll position from the bottom of the content, it behaves like if the content loaded in the other direction.

**Comment by DagAgren** [comment]
Not going to fix any iOS 13 issues until it gets closer to release, as it might very well be an OS bug. Let me know if this keep happening in later updates!

**Comment by tychoquad** [comment]
Understood. I’ll keep an eye on it.

**Comment by DagAgren** [comment]
Ugh, had a little look at it, and I am worried about the state of iOS 13... There are so many internal changes that affect so many different things, and lots of them are subtly broken or changed.

I sure hope there are a lot of bugfixes still on the way but it's getting a bit close...

**Comment by tychoquad** [comment]
There’s been a bit of talk in the tech podcast realm that iOS is in a rough shape for this late in the betas and the new iPhones could end up shipping with 12.4 until 13 improves.

Either way, it’s looking like 13.0 will be one of the roughest launch builds in quite a while. We were spoiled by last year.

**Comment by tychoquad** [comment]
Apple has started public testing of iOS 13.1, indicating that 13.0 is probably finalised and being installed on phones in the factory as I type.

Unfortunately, I don’t think this bug is going away for the release build.

**Comment by DagAgren** [comment]
I think after banging my head against this for days I finally found a fix. Which turned out to be very simple, of course.
