### ISSUE TITLE
Error Uploading panoramic picture

### ISSUE THREAD

**Issue by effeerre75** [DagAgren/toot#338]
In the small uploading picture say:” uploading failed tap to retry”.

![4231F170-2D5E-4E28-A1F6-C9FB14993DD6](https://user-images.githubusercontent.com/16226520/61788111-8c1e8c00-ae11-11e9-925a-e011d54c9ded.png)
![5763D62A-1937-4B03-80EF-F16158C769A8](https://user-images.githubusercontent.com/16226520/61788113-8cb72280-ae11-11e9-82f8-ee48faa128ba.jpeg)

iPhone 6 iOS 12.3.1
Toot! 1.9.0

**Comment by DagAgren** [comment]
I think this is just because the picture is too big for Mastodon. So it depends on this being implemented: https://github.com/DagAgren/toot/issues/55
