### ISSUE TITLE
iPad sidebar gets out of sync when responding to in-app notification

### ISSUE THREAD

**Issue by fluffy-critter** [DagAgren/toot#339]
Kind of a weird corner case but:

1. Be on a timeline view from one server
2. Get a notification banner from another server
3. Tap the notification banner

Now the UI shows a weird situation where the highlighted selection in the sidebar doesn’t match the right panel content (I think it still had the previous view highlighted but was showing the new notification on the right but I wasn’t paying much attention)

**Comment by DagAgren** [comment]
Don't have a tablet around at the moment so I can't test this (notifications don't work in the simulator), but I took a guess at what might cause it and made some changes.

So I'll close this for now, but do complain again if it is still happening once 1.9.2 is out!
