### ISSUE TITLE
Can't login on instance

### ISSUE THREAD

**Issue by mthld** [DagAgren/toot#340]
Hi,

I can't login with the app on my instance: rage.love
The server is running Florence, a v2.9.0 Mastodon fork.
￼
![IMG_6220](https://user-images.githubusercontent.com/41020854/62703285-c62a8900-b9e0-11e9-8345-5ad4ba5c9207.PNG)

Thanks in advance for your help.

**Comment by DagAgren** [comment]
It seems Florence is sending the "max_toot_chars" value as a string rather than as an integer. This is a non-standard Mastodon extension, but other implementation send it as an integer, and that is what Toot! expects to see. I would suggest filing it as a bug with them.

**Comment by mthld** [comment]
@DagAgren many thanks for your help! I'll open an issue on their tracker. 🙆🏻‍♀️
