### ISSUE TITLE
Show warning before opening video on mobile data

### ISSUE THREAD

**Issue by fluffy-critter** [DagAgren/toot#342]
I have to pay for my mobile bandwidth, and sometimes I’ll tap on what looks like a photo only to find that it’s actually a video, too late to stop it from costing me money. It would be nice if there were some indicator as to whether an image is an image or some external media, and if on mobile connections there could be an optional warning before opening the link.

**Comment by 5teveroy** [comment]
I came here to file this problem too, but in my case it's more the annoyance of finding out too late that I started a video and no thanks, I just wanted to see the picture.

A side-annoyance of this is also that Toot! pushes a view controller to display videos, whereas it simply overlays images over the originating view controller.
