### ISSUE TITLE
iPad feature request: Non-modal "sending toot" screen

### ISSUE THREAD

**Issue by VirtualWolf** [DagAgren/toot#347]
My commute to work is an hour on the train, and there's a handful of places where my internet connection becomes a bit spotty. I'll post a toot then have to wait for 30 seconds or more while it sends, and because the animated sending screen is modal, I can't actually do anything else in the app even though my timeline has already loaded and I could keep scrolling through it.

It'd be great to have the sending toot screen just minimise or otherwise allow for the rest of the app to be used while it's sending!

**Comment by DagAgren** [comment]
This would require quite some rearchitecting, so I don't think it will happen any time soon. Might look into making the post panel a separate scene somehow at some point, though.
