### ISSUE TITLE
no notifications iOS 13&13.1

### ISSUE THREAD

**Issue by Tealk** [DagAgren/toot#348]
Hello,

I know I'm using a beta, but I just wanted to point it out. I don't get a notification from any of my 3 accounts. I am using the app in version 1.9.3 and the servers are running 2.9.3 everywhere.

**Comment by tychoquad** [comment]
I’m also running the 13/13.1 beta, and I get notifications fine.

**Comment by Tealk** [comment]
Is there anything special I need to adjust? I have only added the servers.
Since the error occurred to me, I have also switched all notifications off and on again once but I still don't get any of the notification options.

**Comment by tychoquad** [comment]
Have you got them switched on in the settings page for each server?

**Comment by Tealk** [comment]
So 2 user accounts are on one instance and another user account I have on another instance. On all 3 accounts all notification options are activated.

**Comment by tychoquad** [comment]
In settings? Or notifications?

Also, check their switched on in the iOS settings app for toot! In general

**Comment by Tealk** [comment]
i don't know what difference you make between settings and notifications.

Notifications are activated in the app as well as in the ios settings.

**Comment by tychoquad** [comment]
This, VS
![36D49F79-EA00-408A-895B-93205F4E7FF5](https://user-images.githubusercontent.com/16813583/64230796-1e49a200-cf31-11e9-93a0-5931cff1b721.png)
This.
![A8B3C04A-8C73-495F-B433-2E7FDDB76E81](https://user-images.githubusercontent.com/16813583/64230797-1e49a200-cf31-11e9-989a-60d83de29433.png)

**Comment by Tealk** [comment]
![Image](https://i.imgur.com/JTQTt45.jpg)
![Image](https://i.imgur.com/fF4vuvY.jpg)
![Image](https://i.imgur.com/9bU0kyJ.jpg)

**Comment by tychoquad** [comment]
Dunno then, they seem to be on in the settings panel in app, that should do the job.

**Comment by Tealk** [comment]
exactly because i couldn't find a mistake in the settings i write here ;)

**Comment by Tealk** [comment]
hope there will be a solution for that because i think the app is otherwise very nice; the server changer is positioned a little unfavorable for an iphone x/xs

**Comment by Tealk** [comment]
On iPadOS i have the same Problem

**Comment by Tealk** [comment]
No idea what else I could test?

**Comment by Tealk** [comment]
Since the App Amaroq and Web notifications work and I don't get any further support here, I will now ask apple to get my money back.
