### ISSUE TITLE
Photos frequently posted at wrong orientation

### ISSUE THREAD

**Issue by tewha** [DagAgren/toot#349]
Photo taken a few minutes ago on my iPhone X running iOS 13 17A5572a.

As seen in Photos:
![IMG_2356](https://user-images.githubusercontent.com/108106/64368953-2c9acb00-cfd0-11e9-8fc8-948734fff096.PNG)

As posted via Toot:
![IMG_2357](https://user-images.githubusercontent.com/108106/64369021-4e944d80-cfd0-11e9-9c00-c5223d171a6b.PNG)

This could be an iOS 13 bug. I'd test on iOS 12 if I could. :)

iOS 13 17A5572a
Toot 1.9.3 (93)
AppDot.net (v2.5.0)

**Comment by tewha** [comment]
Just happened to a friend with an iPhone XR and the 13.1 beta as well.

**Comment by DagAgren** [comment]
Can't reproduce this as I don't have an iOS 13 device yet, but I made another change that might happen to fix it, so I'll close for now and let's see once the next version is out if it is actually fixed.

**Comment by tewha** [comment]
Toot last updated 8 days ago.

![35D95809-4F73-4294-B6C0-68ADF399F5B3_1_105_c](https://user-images.githubusercontent.com/108106/65392966-e6639c80-dd2f-11e9-8d38-f132ace3c84e.jpeg)

**Comment by DagAgren** [comment]
Make sure you are using the latest version.

**Comment by tewha** [comment]
I got an update today and it’s still doing it. I’ll attach a screenshot when I get home… Not sure how to do that mobile.

**Comment by tewha** [comment]
Actually, I can totally just post a link, can’t I?
https://appdot.net/@tewha/102842758459956836

**Comment by tewha** [comment]
It pains me to say this, but I might’ve been wrong here. Let me see if it happens again.
