### ISSUE TITLE
Poll option preview text is broken in Mastodon theme

### ISSUE THREAD

**Issue by DysphoricUnicorn** [DagAgren/toot#350]
When creating a poll with the mastodon theme selected, the option preview text is white, just like the background.
Steps to reproduce:

1. Change theme to Mastodon
2. Create a new post 
3. Attach a poll
4. Write inside a poll option

Tested on an iPhone XR and an iPad (2018) on iOS 12.4 and 12.4.1 respectively 

![D246D118-EB96-484C-9B27-C1A79BAD43C9](https://user-images.githubusercontent.com/7807969/64439599-9ac3b880-d0ca-11e9-9dd3-0066bf690446.jpeg)

**Comment by DysphoricUnicorn** [comment]
Well, that’s weird.

I‘ve been able to reproduce it with the steps listed above on an iPhone 7 on iOS 12.4.1 as well.

Are you using the latest iOS version on your testing device?
Maybe it has something to do with cached data from before I upgraded the app and your testing setup is „clean“? I obviously don’t know your codebase so that’s just a not very educated guess.

**Comment by DagAgren** [comment]
Well, I could reproduce it ONCE. Now it is of course not happening any longer.

**Comment by DagAgren** [comment]
Hmm. That may be because I actually fixed this and forgot that I did!
