### ISSUE TITLE
Redirected media fails to load

### ISSUE THREAD

**Issue by multiple-creatures** [DagAgren/toot#352]
Toot! sometimes has trouble following redirects on media assets, which causes loading them to fail or stall.

This affects instances using shared storage hosts such as [Jortage](https://jortage.com/) that make use of redirects pointing to assets' real public URLs.

![2019-09-16 20-22-40-1](https://user-images.githubusercontent.com/30352165/65003953-41286e80-d8c0-11e9-9b62-302d793b469f.JPG)
![2019-09-16 20-22-40-2](https://user-images.githubusercontent.com/30352165/65003954-41c10500-d8c0-11e9-874b-afd824fb6179.JPG)
![2019-09-16 20-22-40-3](https://user-images.githubusercontent.com/30352165/65003955-41c10500-d8c0-11e9-97e3-f58e33c83958.JPG)

**Comment by wolfteeth** [comment]
I'm also seeing this issue on an instance using Jortage.

**Comment by doppled** [comment]
I'm also getting reports of this from some of my users on instances using jortage.

**Comment by DagAgren** [comment]
Trying to have a look at this now but I need a way to reproduce this. Where is it happening?

**Comment by wolfteeth** [comment]
@DagAgren I saw it on Monsterpit.net.

**Comment by DagAgren** [comment]
monsterpit.net doesn't seem to let me view the timeline. Anywhere else?

**Comment by doppled** [comment]
The whole list of instances using jortage can be found at https://jortage.com

It should be reproducible on any of them.

**Comment by DagAgren** [comment]
I can't seem to reproduce it. I tried toot.cat and lgbtq.cool, and images seem to load fine on both?

**Comment by doppled** [comment]
This seems like a silly question but you tried from a local account on those servers? Cuz youd have to be logged into the affected server to see the issue.

**Comment by DagAgren** [comment]
I'm adding them as instances and viewing the public timeline. Should be the same as being logged in.

**Comment by doppled** [comment]
Yeah hmmm that should be the same but weird. I just checked n one of my users is still having the issue tho
Seems to me like the next step would be to try and reproduce the issue by doing actually what users are doing to get it then :woman_shrugging:

**Comment by DagAgren** [comment]
If anyone can find a reliable way to reproduce this, that would be really useful.

**Comment by ilovecomputers** [comment]
I’m on nulled.red and I notice this issue on remote follows. The media of a remote account loads fine on first try, but on subsequent attempts the media disappears. This happens avatar and banners of remote accounts as well. Maybe attempt again on a federated timeline inside those instances that use jortage

**Comment by wolfteeth** [comment]
What I experienced was similar to what @ilovecomputers reported. Media would load at first, but if I switched accounts away from the affected instance and back again, the media would not load anymore. It was the case for both local and remote media, including my own uploads.

**Comment by bluexenologer** [comment]
This is still happening. @DagAgren would it be useful for you to make an account on one of these instances to do exactly the interaction we are? Maybe viewing the remote timeline is supposed to be the same but evidently there is some tiny fiddly difference.

**Comment by DagAgren** [comment]
FINALLY managed to reproduce this properly.

The problem was, the FIRST load works just fine, it's only subsequence loads from the cache that were failing. Figured out what was happening and managed to fix it. Should be in 1.11.2 (or 1.12, depending on which it ends up being).
