### ISSUE TITLE
Switching to dark mode sometimes doesn’t trigger correctly

### ISSUE THREAD

**Issue by tychoquad** [DagAgren/toot#353]
I’ve noticed that when using the toot! Theme, the bottom bar usually doesn’t change to dark mode when switching. Oddly enough, while this bug was in effect, I switched back to lite mode on my first instance and the bottom bar went dark. Didn’t seem to effect the others

**Comment by fihu** [comment]
To elaborate: the bottom bar does not switch over to dark when iOS dark mode is turned on while toot! is running. After close & reopen, the bottom bar is dark.

However, the top bar always stays bright.

**Comment by DagAgren** [comment]
Is that something that you actually do in normal usage, switch between the two modes?

**Comment by tychoquad** [comment]
I don’t use dark mode at all, but it was new, so I wanted to test it.

**Comment by fihu** [comment]
I'm usually getting some graphic errors, when opening Toot after it was suspended in dark mode and is now switching over to light mode.

Mode switching errors seen:
- bottom bar background not switching to other mode. Icons do switch tho.
- black borders around the 'show more' bar (probably light bars when switching from light to dark)

Other observations:
- Top bar always stays in light mode. Might switch like bottom bar.

**Comment by tonilampela** [comment]
> I'm usually getting some graphic errors, when opening Toot after it was suspended in dark mode and is now switching over to light mode.
> 
> Mode switching errors seen:
> 
> * bottom bar background not switching to other mode. Icons do switch tho.
> * black borders around the 'show more' bar (probably light bars when switching from light to dark)
> 
> Other observations:
> 
> * Top bar always stays in light mode. Should switch like bottom bar.

I also see glitches mentioned above. Most commonly the black borders around “show more”. 
![8C52778F-F46D-440B-B381-97E27C62FF2F](https://user-images.githubusercontent.com/930866/65813081-d7219a80-e1d8-11e9-9d4c-20c6caffd978.jpeg)
