### ISSUE TITLE
Light reply map option keeps turning on

### ISSUE THREAD

**Issue by cbane** [DagAgren/toot#354]
I've hit a problem a number of times where the "Light reply map" setting turns on by itself. Some times I can go several weeks without it happening, but I've seen it happen after just a few minutes.

**Comment by cpsdqs** [comment]
I thought this too, but turns out it’s because (accidentally) tapping the railroad lines in the conversation view will actually toggle the setting on or off.

**Comment by DagAgren** [comment]
Yeah, you can switch it directly that way.
