### ISSUE TITLE
Tooting interface gets weird on iOS 13 and iPhone XR

### ISSUE THREAD

**Issue by fluffy-critter** [DagAgren/toot#355]
It looks like on iOS 13 the photo attachment facet gets detached from the keyboard and ends up partially covering the toot button. 

![6AC0710F-FC0B-4872-8626-1362B3F461BD](https://user-images.githubusercontent.com/347162/65375856-8cd77100-dc4e-11e9-897d-4cb29103dcdf.png)

**Comment by DagAgren** [comment]
This sounds like an iOS 13 bug. You don't get much in the way of control over where to place that bar.

**Comment by fluffy-critter** [comment]
Yeah, turns out it was transitory too. I haven’t seen it happen again.
