### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by mediaformat** [DagAgren/toot#358]
CW text is illegible in dark mode: white text on yellow striped background

**Comment by DagAgren** [comment]
Which theme?

**Comment by mediaformat** [comment]
IOS theme for Toot, but I have set to Dark in OS Settings->Display & Brightness->Appearance

**Comment by DagAgren** [comment]
Does this only happen when you actually switch to dark mode?

**Comment by mediaformat** [comment]
Ah I see what you mean. Yesterday I updated the OS, started using Dark mode right away, and noticed white text of yellow and light grey stripes. Now I am in dark mode again and the stripes are yellow and dark grey, it's perfect. 
However manually switching to light mode with the app opened, the preloaded toots have the wrong background.
Can probably close this, it seems a bit of an edge condition.

**Comment by DagAgren** [comment]
I've been slowly fixing these kinds of bugs because they do get a little annoying if you have your phone set to switch to dark mode at night.
