### ISSUE TITLE
iOS app missing on Hungarian AppStore

### ISSUE THREAD

**Issue by RazrSaw** [DagAgren/toot#361]
Hello,

I can not find the app in the Hungarian app store on iOS.
Can you make it available?

Thanks in advance!

**Comment by DagAgren** [comment]
I have not limited it any way, so I don't know why it wouldn't be there?

**Comment by DagAgren** [comment]
<img width="203" alt="Screenshot 2019-11-04 at 16 36 20" src="https://user-images.githubusercontent.com/11536828/68128896-451c5880-ff21-11e9-863b-56068853d0af.png">
