### ISSUE TITLE
App Crashes on Startup

### ISSUE THREAD

**Issue by tdapple** [DagAgren/toot#368]
I installed the app, it got to where I pick my server (fosstodon.org) once I did, the app crashed. Since then it crashes on startup. I did a reboot of the phone also to check. 

I have an iPhone 8 Plus
iOS version: 13.1.3

toot! version: 1.10.2

**Comment by DagAgren** [comment]
This is a weird one. I can see two crashes that match your specs, but neither looks quite like it. One is a crash when pressing the Home tab, which doesn't seem to match your description. The other one is really weird: It is crashing outside of my code, while doing a transition, inside something called "__CRASHING_DUE_TO_PRIVACY_VIOLATION__" while trying to communicate with an external process.

Given that iOS 13 is in quite a sorry state, could you first try upgrading to the latest iOS version just to make sure we are not dealing with yet another random iOS bug?

**Comment by tdapple** [comment]
Didn't even realize I was an update behind on iOS.. doing it now and will test.

**Comment by tdapple** [comment]
So I did the update and it crashed when I tried to open it again. I then removed the app and reinstalled. It is working now.

**Comment by DagAgren** [comment]
Very weird. I am just going to hope it was an iOS 13 hiccup and it messed up the permissions for the app. Let me know if it starts acting up again!
