### ISSUE TITLE
Feature Request: Allow following users from other instances

### ISSUE THREAD

**Issue by horsemans** [DagAgren/toot#369]
Hello, and thank you for such a fantastic app!

I have a small request: when viewing the timeline of an instance you’re not logged into, you can boost and favorite tweets from a logged in account. However, if you tap on the tweet’s user, that pop-up should be allowed for this currently-disabled ‘FOLLOW’ button.

![FB5B58D1-B550-43B1-A5D2-AF394B53DC92](https://user-images.githubusercontent.com/47841583/70003686-e94deb00-1531-11ea-9c38-26ab7f73db0c.jpeg)
![BF43DC1A-D3CF-4483-84D2-778D24BB497D](https://user-images.githubusercontent.com/47841583/70003687-e94deb00-1531-11ea-99ee-e5606781d0fd.jpeg)

**Comment by tychoquad** [comment]
If you search for them from a logged in server, you can follow them from there. It’s not as convenient, but it works
