### ISSUE TITLE
Share sheet UI confusing

### ISSUE THREAD

**Issue by davmillar** [DagAgren/toot#373]
The UI for share sheet is confusing when choosing the account to post to. I kept getting confused as to why it kept picking the wrong account. Turns out the UI chooses whichever bar you tap on, and doesn’t dismiss it if you hit the X. So for example, if I tap the X circled in the screenshot below, it will actually choose that account, not dismiss it.
![E1F50FD8-4F52-446D-B309-ADD7FCA1D335](https://user-images.githubusercontent.com/576958/71303065-6d4d0300-2379-11ea-9211-6628d72c7377.jpeg)
One possible solution would be to simply hide the X until an account is chosen, but the way the two modals appear offscreen feels glitchy rather than a design choice, so maybe there’s an opportunity for a different account selector.

**Comment by DagAgren** [comment]
I don't think this is a big enough issue to be worth reworking.
