### ISSUE TITLE
Feature request: support various web browsers to open links

### ISSUE THREAD

**Issue by dahlia** [DagAgren/toot#378]
It would be great if Toot has browser settings — I want to open links using Firefox.  Indeed quite many iOS apps has the same thing.  E.g.:

### Tweetbot

<div><img src="https://user-images.githubusercontent.com/12431/46594935-e3689f80-cb10-11e8-82df-82b48da24625.PNG" width="50%"><img src="https://user-images.githubusercontent.com/12431/46594936-e4013600-cb10-11e8-9aca-082821e71080.PNG" width="50%"></div>

### IRCCloud

<div><img src="https://user-images.githubusercontent.com/12431/46594989-2b87c200-cb11-11e8-9117-ff999452050e.PNG" width="50%"><img src="https://user-images.githubusercontent.com/12431/46594990-2b87c200-cb11-11e8-997c-4874b12301ba.PNG" width="50%"></div>

### Slack

<div><img src="https://user-images.githubusercontent.com/12431/46595035-6db10380-cb11-11e8-9e96-5edf395f311d.PNG" width="50%"><img src="https://user-images.githubusercontent.com/12431/46595036-6e499a00-cb11-11e8-9672-6e1f27679471.PNG" width="50%"></div>

### Reddit

<div><img src="https://user-images.githubusercontent.com/12431/46595033-6db10380-cb11-11e8-8b4d-58f6e95bd0b7.PNG" width="50%"><img src="https://user-images.githubusercontent.com/12431/46595034-6db10380-cb11-11e8-879f-364e20f84311.PNG" width="50%"></div>

----

[Originally I left a comment of the same request in the other issue, but as it was closed][1], I opened this separately.

[1]: https://github.com/DagAgren/toot/issues/167#issuecomment-427735126

**Comment by DagAgren** [comment]
Not sure I want to do this - it seems like it would be a maintenance nightmare to keep it working right.

**Comment by dahlia** [comment]
Although I don't have much experience in iOS development, IRCCloud's source code might be helpful… They have classes like [`OpenInChromeController`](https://github.com/irccloud/ios/blob/RELEASE_4.13/OpenInChrome/OpenInChromeController.h) & [`OpenInFirefoxControllerObjC`](https://github.com/irccloud/ios/blob/RELEASE_4.13/OpenInFirefoxClient/OpenInFirefoxControllerObjC.h), and fortunately these classes seem to haven't changed for several years.

**Comment by DagAgren** [comment]
Unfortunately, I don't think this is worth the effort as things stand.
