### ISSUE TITLE
Option to open profile in browser.

### ISSUE THREAD

**Issue by davmillar** [DagAgren/toot#381]
It would be nice if there were an option to view a profile in the browser.

I often get favorites and boosts from people I don’t know and which have no toots my instance knows about yet. This feature would allow me to more easily check out other folks and see if they’re worth following.

**Comment by DagAgren** [comment]
Interesting idea. I mean, ideally there would be an option to just load the data from the remote instance, but I think Mastodon still does not allow you to load user timelines without logging in?

**Comment by DagAgren** [comment]
Oh wait, I misremembered, that was enabled. So it could be done that way instead. How does that sound?

**Comment by davmillar** [comment]
That would be a nice solution to my immediate problem as well.

**Comment by DagAgren** [comment]
Actually, that seems to be more work than it's worth. But I guess it make sense to add a "Share..." option like the one on toots, and from that you should be able to open the link in a browser.
