### ISSUE TITLE
Backgrounding in thread loses scroll position 

### ISSUE THREAD

**Issue by chucker** [DagAgren/toot#383]
1. Go inside a thread
2. Scroll down as you read replies
3. Switch apps
4. Come back to Toot

It briefly shows your previous position, then scrolls to the top of the thread.

**Comment by DagAgren** [comment]
I can't reproduce this.

**Comment by chucker** [comment]
Really? I just tried it with a few more threads.

https://share.icloud.com/photos/0j1R1E_KKx76-0p8EzusbhivQ

**Comment by DagAgren** [comment]
Which app and iOS version is that?

**Comment by chucker** [comment]
iOS 13.4 beta (17E5255a)

Toot! v1.11.1 (116)

I _think_ I wasn't on an iOS beta when I originally filed this, but I'm not entirely sure.

**Comment by DagAgren** [comment]
Weird, I was sure I couldn't get it to happen, but now I can. Also, fixed!
