### ISSUE TITLE
iPad: Notifications selector popup goes wonky on splitscreen

### ISSUE THREAD

**Issue by fluffy-critter** [DagAgren/toot#389]
If the iPad client is in splitscreen view, the selector popup for notification types gets rendered without a background and fills the full width of the pane. This happens for any split width (25/50/75%).

<img width="1112" alt="tootapp split screen bug" src="https://user-images.githubusercontent.com/347162/75291049-54782800-57d6-11ea-8ebb-77d57d959c29.png">

**Comment by DagAgren** [comment]
Eesh, what an annoying edge case, iOS just decides for you that in split screen, you don't REALLY want popup bubbles.

Added an override for it. Let me know if you find any other cases where it happens!
