### ISSUE TITLE
Sensitive media switch will not turn off

### ISSUE THREAD

**Issue by 0xafaebabe** [DagAgren/toot#390]
1. Open Toot! using iOS 13.3.1 on an iPad Pro 12.9”
2. See sensitive media in timeline
3. Go to settings
4. Turn off “always show sensitive media”—toggle switches to off state correctly
5. Scroll up and down
6. “Always show sensitive media” toggle has reset back to on state

**Comment by DagAgren** [comment]
Fixed!
