### ISSUE TITLE
Filter posts that are not directed at you (Pleroma)

### ISSUE THREAD

**Issue by JanJastrow** [DagAgren/toot#391]
Hi there,
1. Thank you for this app, it's still my go-to app for the fediverse
2. I know that Toot! is primarily a Mastodon client and Pleroma compatibility is just 'nice to have' - still, I'd like to open a issue for this

## Description
Per default, Pleroma delivers all replies from everyone you are following to your timeline (this also includes replies to people you are *not* following).
The Pleroma web interface allows you to set filters for this, but it seems they only apply to the web UI.

I would love to have an option to filter this in the app as well.

[Screenshot of the filter in the pleroma interface.](https://cloud.ministeriumfuerinternet.de/s/bXkSRHHfsiQtJxe)

### Edit

This could also be a valid filter option for a mastodon timeline.
Maybe someone don't want to see any replies (at them / someone else) in their timeline.

**Comment by DagAgren** [comment]
Hmm, with the current architecture, filtering timelines is not really easy to accomplish.

**Comment by DagAgren** [comment]
So unfortunately, I don't think this will happen now, unless Pleroma has some way to request a timeline with them filtered out.

**Comment by jsit** [comment]
@DagAgren Is one even able to hide replies and/or boosts on a Mastodon account?
