### ISSUE TITLE
Toot input: selecting a hashtag removes a space character

### ISSUE THREAD

**Issue by claus** [DagAgren/toot#392]
When i compose a toot, and start entering a hashtag (e.g. `Hello #mastod`), and then select one from the list that appears below (e.g. #mastodon), the space character that immediately precedes the # is deleted (i end up with `Hello#mastodon`)

**Comment by mthld** [comment]
Hi,

I can reproduce this, it's a bit annoying to format text with hashtags in it because of this issue.

**Comment by DagAgren** [comment]
Fixed!
