### ISSUE TITLE
Wrong conversation threading

### ISSUE THREAD

**Issue by futzle** [DagAgren/toot#393]
This conversation shows different conversation threading depending on which toot I am viewing.

Single toot by yellow user in response to my original toot about figs:
![IMG_7381](https://user-images.githubusercontent.com/10947921/77974582-45d7e000-7343-11ea-910c-b84ec62fe862.PNG)

Followup toot (about Shadow the kitten) with two replies by cyan user:
![IMG_7380](https://user-images.githubusercontent.com/10947921/77974587-483a3a00-7343-11ea-9da3-803e871c265a.PNG)

But this view shows yellow user responding to kitten toot and cyan user responding to fig toot, which is exactly backwards.
![IMG_7379](https://user-images.githubusercontent.com/10947921/77974574-3fe1ff00-7343-11ea-9a01-c0224be9a8c8.PNG)

Link to original toot on mastodon.social: https://mastodon.social/web/statuses/103910564233077537

v1.12 (117)

**Comment by DagAgren** [comment]
Hmm. It seems this is kind of a server side issue. Even on the web interface, the replies are in the wrong order. My threading code is not designed to handle replies being out of order.

This is probably just a one-off error, so I don't think it's worth putting in significant effort to improve the threading code. If things change and there are more cases like this, I'll reconsider.
