### ISSUE TITLE
Indicate verified links in profile

### ISSUE THREAD

**Issue by hansvurst-foss** [DagAgren/toot#395]
Hi! Thanks for your awesome Masto client. 🎉 

I kind of miss the Web UI's feature to display the verfication status of the links placed in a users profile. Missing this feature makes it kind of hard to tell whether accounts are real or fake especially in a federated network.
You closed [a similar issue](https://github.com/DagAgren/toot/issues/316) a while a go but maybe there were [some helpful changes](https://github.com/tootsuite/mastodon/issues/10777#issuecomment-493674254) since then?

**Comment by DagAgren** [comment]
I think that as things stand, between the cryptocurrency nonsense and being bought by Zoom, I don't trust Keybase any longer and will not add support for them.

However, the verification status of the regular metadata fields, that should be added.

**Comment by hansvurst-foss** [comment]
Yeah, maybe the links I provided where a little misleading. I never meant Keybase in my request but the simple verified links in the metadata fields. Thanks for addinng those. :+1:
