### ISSUE TITLE
Character count wrong in some cases

### ISSUE THREAD

**Issue by anths** [DagAgren/toot#399]
I had the attached experience a few days ago: Toot’s character count said the post was under 500 characters when it wasn’t, and the server rejected it. I do not see an obvious issue, although I suspect something around URL processing. The third screenshot is from Drafts to verify the character count. 

![BF8E823E-C7C0-4725-BA54-407C7A8E0C0B](https://user-images.githubusercontent.com/1130492/79789094-8d2c0d80-82fe-11ea-805e-42ded2d2c646.png)
![5A183F81-13B9-4A8F-801F-48141576FA3E](https://user-images.githubusercontent.com/1130492/79789122-961cdf00-82fe-11ea-858d-72a74729d636.png)
![9639E6D3-0936-4465-B68F-848293543F5D](https://user-images.githubusercontent.com/1130492/79789139-9ae19300-82fe-11ea-98de-c6485c7d6336.png)

**Comment by DagAgren** [comment]
This is really hard to get exactly right. I'd need some more information on how exactly the counting methods differ to be able to do anything...

**Comment by anths** [comment]
I did a few more tests. It does look like it’s related to URLs. The spec says there always counted as 23 characters, but it looks like Toot is counting then as 22, at least in some cases I found (possibly any case except when they begin a post?).

**Comment by DagAgren** [comment]
Oh yes, that's it. The Twitter URL regex I'm using to detect links is weird and includes the character before the link as well, so we end up miscounting by one if there is a character before the link.

Fixed now.
