### ISSUE TITLE
Text is displayed on top of avatar in home view

### ISSUE THREAD

**Issue by mauromorales** [DagAgren/toot#404]
![image](https://user-images.githubusercontent.com/433958/82105031-92bc1e00-9719-11ea-86f1-a37cdf2b7156.jpeg)

I’m using an iPhone 7

**Comment by DagAgren** [comment]
Need some more information to reproduce this.

**Comment by mauromorales** [comment]
@DagAgren seems to be working again, not sure if it was related to the last OS update or simply my phone being silly. Will close for now, thanks for checking it out!
