### ISSUE TITLE
Feature request: support for drafts

### ISSUE THREAD

**Issue by a-dows** [DagAgren/toot#405]
The ability to save draft posts is offered by other mastodon apps and is a hallmark of twitter apps as well. Drafts should support media attachments and their captions.

Closing an in-progress toot in the compose view should prompt to save as a draft, and the draft list should be incorporated in the compose options. The draft list should include time stamps for when the drafts were last edited.

**Comment by DagAgren** [comment]
This is too much design and implementation work for a too small benefit to really be in scope at the moment. I simply do not have the time.
