### ISSUE TITLE
Titlebar intermittently becomes unresponsive

### ISSUE THREAD

**Issue by vulcoes** [DagAgren/toot#413]
After tapping on a toot, the titlebar will intermittently stop working (image 1). The only workarounds that allow one to navigate back to the timeline or previous toots is to switch to the Notifications tab then back to the toots, which results in buggy visuals (image 2, 3), or to force quit the app. 

![8190EED4-B0EB-4B8D-8FD2-B8C96206799E](https://user-images.githubusercontent.com/3402003/85324133-23ef8480-b47e-11ea-965b-5560300e43a1.jpeg)

![DCAA27B7-1474-43E2-BEFC-0CA0F56D6647](https://user-images.githubusercontent.com/3402003/85324135-2520b180-b47e-11ea-8029-10f97280cff1.jpeg)

![257487A3-CB81-4F63-B47B-8E804740A621](https://user-images.githubusercontent.com/3402003/85324137-2520b180-b47e-11ea-9586-39320c272b50.jpeg)

**Comment by DagAgren** [comment]
Which iOS version is this?

**Comment by alangarciar** [comment]
It was happening on all versions of iOS 13 on my SE (1st generation), these screenshots are from 13.4.1. I’ve updated to 13.5.1 today so I’ll use it normally and see if it persists

**Comment by DagAgren** [comment]
There's something very weird happening here. Is there anything unusual about the phone at all?

**Comment by vulcoes** [comment]
I mean, I recently cracked the screen and removed the glass, but this was happening beforehand as well. There are no jailbreaks, cases, screen protectors, or screen replacements.

**Comment by DagAgren** [comment]
I've never seen anything like this. As far as I can tell, there isn't even any way for an app to get into the kind of state that is shown in the screenshots. I really have no idea what is going on here, and I have heard no other reports of this either, so there must be some weird little detail that triggers this, but I have no idea what it would be.

**Comment by DagAgren** [comment]
Is this still happening?

**Comment by vulcoes** [comment]
Sorry for the late reply! I got a new phone, so I doubt I’ll be able to reproduce it and the 1st generation SE is probably a small minority of your user base anyway, so I’m ok with closing the issue.
