### ISSUE TITLE
Tapping DM bubble crashes Toot! v1.13 (121)

### ISSUE THREAD

**Issue by MacLemon** [DagAgren/toot#414]
# Summary:
Tapping DM bubble crashes Toot!

## Steps to Reproduce:
1. Get a DM on Mastodon
2. See a round bubble float above your timeline view in the top right hand corner.
3. Tap bubble
4. Toot! crashes

## Expected Results:
I don't know yet what the bubble is for, but Toot! should not crash upon tapping it.

## Actual Results:
Toot! crashes!

## Regression:
n/a since that bubble is a new addition in the update to v1.13 (121)

## Notes:
n/a

## Version Information:
Toot!: v1.13 (121)
Mastodon Server: 3.1.4
iOS: 12.4.7 (16G192)

**Comment by DagAgren** [comment]
Well, it's not going to be quite that simple, unfortunately. It works fine everywhere I've tested it... What device do you have? Is it not handling the CIImage stuff I use for the transition there, maybe?

**Comment by MsCupcake** [comment]
It does the same for me, crashes to the home screen when you tap on the DM bubble: I'm on iPhone 6, software version 12.4.6

**Comment by DagAgren** [comment]
Then this is probably caused by some very old and tired phones.

**Comment by DagAgren** [comment]
Tried to add some GPU detection so I can disable the more strenuous effects on senior phones, that should hopefully stop the crashing.
