### ISSUE TITLE
Bring back viewing profile pictures in full size

### ISSUE THREAD

**Issue by fireglow** [DagAgren/toot#421]
I'm visually impaired and need the profile pictures and header pictures to enlarge on a tap, so I know what I'm looking at.

**Comment by DagAgren** [comment]
Already fixed.

**Comment by MsCupcake** [comment]
Still doesn't work for me, tapping on a profile pic or header doesn't do anything.

**Comment by MsCupcake** [comment]
I checked the app store before posting to make sure— of course the update appeared afterwards! All fixed
