### ISSUE TITLE
Refreshing home feed will sometimes open link in the top toot

### ISSUE THREAD

**Issue by stayinside** [DagAgren/toot#422]
This is has been hard for me to reproduce but happens once and a while. I think the top toot has to be new content and a specific way of refreshing the home feed has to happen that I can’t quite figure out. If I figure out more info I’ll add to the issue.

**Comment by DagAgren** [comment]
Are you sure your screen is not just having some touch issues and thinks you let go for a second and registers it as a tap?

**Comment by stayinside** [comment]
I haven't experienced touch issues of any kind in any other app.

**Comment by DagAgren** [comment]
Very weird! Let me know if you figure out anything more.

**Comment by stayinside** [comment]
Figured it out and I feel like a dork.

I think it happens when you pull down on the feed with your thumb over a link. The open-in pop-up happens after the refresh giving the illusion of an automatic process. It was user error after all never mind.
