### ISSUE TITLE
Unable to share media(image, video) via share sheet

### ISSUE THREAD

**Issue by Canorus** [DagAgren/toot#425]
iOS share sheet crashes when tried to share media via share sheet. It's not HDR content ( #292 ) and it's only happening when sharing to Toot! app. Link to screen recording is attached——Github doesn't seem to support MP4 format. Affected device is iphone X, iOS 13.5.

[screen recording of sharing sheet crashing when sharing image from reddit app](https://d.pr/v/trMJbu)

[screen recording of sharing sheet crashing when sharing video from twitterrific](https://d.pr/v/NJVGuI)

[and it's only happening with Toot!](https://d.pr/v/pv83Pg)

**Comment by DagAgren** [comment]
Fixed!

**Comment by Canorus** [comment]
Thank you for your hard work!
