### ISSUE TITLE
Watching a gif pauses currently playing audio

### ISSUE THREAD

**Issue by optikfluffel** [DagAgren/toot#426]
When I‘m playing music or a podcast and open a gif in Toot! it pauses the music until I dismiss it and watch the timeline again.

**Comment by DagAgren** [comment]
I can't reproduce this. Music is paused if you open a video with sound, but not if you open a GIF.

(GIFs will autoplay on the timeline, but videos with sound will not, that is how to tell the difference.)

**Comment by optikfluffel** [comment]
Ok, then something else must be broken on my end, because I never saw an autoplaying gif in Toot!. All gifs are only grey squares with a question mark in them, until I tap and open them up full screen (but also my audio stops while doing so).

Is there any way I can help you debug this, maybe get some logs out of this phone or so?
