### ISSUE TITLE
Notifications use profile picture

### ISSUE THREAD

**Issue by aurynn** [DagAgren/toot#427]
So, this is an enhancement, but it'd be nice if iOS notifications didn't use the users' profile picture as the media entry.

Expanding the notification normally on iOS, and the notification just explodes into a giant PFP, which is not a great UX.

It'd be great if a media attachment could only be applied to the notification if there's media attached to the toot - otherwise, not attach media.

**Comment by DagAgren** [comment]
That data is unfortunately not included in the actual notification payload.

It might be possible to load the actual toot and then load the image, but notification services are time-limited and if they do not finish processing the notification quickly enough, the default content will be displayed, which in this case is an basically empty notification as the actual notification data is the encrypted web push payload which is sent in the metadata.

So I am a bit reluctant to try too much fancy loading there, as it could break the basic functionality.

**Comment by aurynn** [comment]
That makes complete sense, and sounds like it'd be too much of a hassle to implement.

Would it be possible to not display the PFP at least? 🙂 (Or make it a toggle?)

Thanks!

**Comment by DagAgren** [comment]
I think I'll close this for now but for a possible future notification revamp I will be considering options.
