### ISSUE TITLE
Unable to set image description when shared from Photos app

### ISSUE THREAD

**Issue by stayinside** [DagAgren/toot#428]
When in photos app, if you share an image to toot! and then tap the uploaded image to set a description toot! will close and user is returned to the share screen.

**Comment by DagAgren** [comment]
Is this the same issue as https://github.com/DagAgren/toot/issues/292 ? What iOS version are you on?

**Comment by stayinside** [comment]
It seems that it is the same issue, but happens even without HDR. Screenshots and downloaded pictures work as expected.
I’m currently on ios 13.5

**Comment by fihu** [comment]
I can confirm that this happens in iOS 14 as well.
Camera photos in HDR and without crash Toot! when shared from the Photos app once I try to edit the image's description.
It does work when using a different .jpeg, eg. one saved when posting to Instagram (so the file creator is Instagram).

**Comment by DagAgren** [comment]
I managed to implement a different version of the focus selection view that does not trigger this weird iOS bug, so this should work again. It will look slightly different from the main app, but that'll have to do.
