### ISSUE TITLE
Does not display lists in rich-formatted toots

### ISSUE THREAD

**Issue by tinycalcifer** [DagAgren/toot#432]
In toots that have bulleted or numbered lists (such as are generated from Markdown-supporting Mastodon forks), the list text is displayed without formatting. 

For example, given https://hackers.town/@calcifer/104484752927124601

Expected (web interface): 
![4EF2496A-FCCF-4C2E-A894-2C705FAFE360](https://user-images.githubusercontent.com/62311832/87231218-c793cc80-c37a-11ea-87f8-eafe19c85bd5.png)

Actual: 
![3FB2397B-835A-4472-AC18-1704CF167292](https://user-images.githubusercontent.com/62311832/87231200-a3d08680-c37a-11ea-9fda-a41fe8291019.png)

**Comment by DagAgren** [comment]
This is not a Mastodon feature, and since this is primarily a Mastodon client, I don't think I will be adding this. It interferes with certain other features like copying the toot text, as well.
