### ISSUE TITLE
Allow selecting text within Toot body

### ISSUE THREAD

**Issue by karthanistyr** [DagAgren/toot#434]
It would be useful to be able to select text using the native text selection mechanism within a toot, i.e. long press to invoke the caret and then drag/select as needed, copy or lookup (dictionary), etc...

It is currently possible to copy the entire toot by way of menu, but selecting a word or a sentence isn’t possible at the moment (or I fail at it...).

**Comment by DagAgren** [comment]
This would require a lot of work to implement, unfortunately, and I think I have to budge the time I have available to work on things, and the payoff for this is a bit too small to consider it as things stand.
