### ISSUE TITLE
Feature request: allow debouncing/double-tapping/hiding favorite button

### ISSUE THREAD

**Issue by cpsdqs** [DagAgren/toot#435]
I often find myself accidentally favoriting random posts with an errant tap on the screen, so it would be nice if there was an option for one of:

- (a) debouncing the action buttons such that they do not immediately send an action, and can be canceled for a short period of time
- (b) the double-tap-to-boost but for favorites (there seems to be no way to cancel the bigger button size, though?)
- (c) completely hiding action buttons in timeline views

**Comment by gmshh** [comment]
+1 on specifically “double tap to boost” being implemented as an option for favourites as well.

**Comment by DagAgren** [comment]
Yeah, I guess that makes sense to do. I'll make that option apply to both.
