### ISSUE TITLE
Provide option to visually distinguish & hide toots by bots/automated accounts

### ISSUE THREAD

**Issue by cortices** [DagAgren/toot#436]
Mastodon supports a boolean value in account profiles of whether an account is run by an automated service or bot. Many such bots are Markov-chain generators ("ebooks bots"). These accounts are often made to resemble accounts run by real people, save for setting the 'bot' profile flag. Some bot operators add CWs to all toots by Markov bots indicating that it is computer-generated content, but this is not common let alone universal.

Autistic people such as myself, and those with various other neurodiverse conditions (schizophrenia, paranoia, CPTSD, etc) can be stressed out and/or triggered by the meaningless and often quasi-nonsensical output of these bots. A mechanism to automatically hide all toots by bot accounts behind a banner (like CWs) or to simply apply a client-side CW to all toots by bot accounts would be welcomed. Also suggested would be the ability to enable a visual change of the profile icon and/or display name to clearly indicate the account is a bot. This could take the form of a 'badge' on the icon, replacing the account icon entirely with a specific bot image, adding an icon before the display name, or something else.

#### In Mastodon
There was a [merged PR on tootsuite/mastodon](https://github.com/tootsuite/mastodon/commit/4b794e134d427dbc716606324adb9a885a74abec) that added a bot icon beside avatars belonging to bot accounts but this seems to have been [reverted shortly afterward](https://github.com/tootsuite/mastodon/commit/3d7f68c273f03497ff555acac70355ba1815f7a2).
I'm not sure of the reasoning behind this reversion but I can confirm that mastodon 3.1.2 on cybre.space does not display a visual badge on bot accounts.

**Comment by DagAgren** [comment]
This does sound like a reasonable feature. Not sure what exact form would make sense, but I'll try to think it through.

**Comment by DagAgren** [comment]
Added a settings flag to add "Bot account" to the content warning on any bot post, even if it was originally empty.
