### ISSUE TITLE
SHOW ALL not just SHOW MORE more toots

### ISSUE THREAD

**Issue by frankgerhardt** [DagAgren/toot#437]
Please, instead of SHOW MORE toots, load **all** missing toots because the usability of repeating the SHOW MORE process is a nightmare. 

_Originally posted by @frankgerhardt in https://github.com/DagAgren/toot/issues/229#issuecomment-664028691_

**Comment by frankgerhardt** [comment]
My equally evil workaround is to click SHOW MORE and then scroll down quickly to that it is not visible any more. Then my reading position is preserved at the bottom. But if I'm not fast enough, my reading position jumps to the top of the loaded toots and I cry.

**Comment by DagAgren** [comment]
This is very risky, as it could trigger hundreds of requests to the server, causing massive load for servers already running on a shoestring budget.

Unfortunately, you will just have to live with the current solution.

**Comment by VirtualWolf** [comment]
@frankgerhardt It's fairly subtle and I didn't notice it at first when it was introduced a while ago, but you can choose which direction the toots will load in by checking which way the two arrows are pointing when it says "Show more". :)

**Comment by frankgerhardt** [comment]
> This is very risky, as it could trigger hundreds of requests to the server, causing massive load for servers already running on a shoestring budget.

That is not the client's reposibility. It looks like this would solve somebody else's problem. The server might have rate limiting, or not, or it resonds artificially slow, which would probably be faster than toots can be read.

**Comment by frankgerhardt** [comment]
> @frankgerhardt It's fairly subtle and I didn't notice it at first when it was introduced a while ago, but you can choose which direction the toots will load in by checking which way the two arrows are pointing when it says "Show more". :)

Yes, subtle. But that reliefs my pain. At least it's not jumping around.
