### ISSUE TITLE
Unable to add Pleroma-based server if admin email is empty

### ISSUE THREAD

**Issue by Flameborn** [DagAgren/toot#442]
When adding a new server by typing its url into the search field, just before user authentication, Toot displays: "Unable to load server.", if the admin email field is empty.

Tested via Pleroma 2.1. I am not sure if this also applies to the official Mastodon server.

I think it would be a lot more informative if Toot could display the reason why the server cannot be added in this case, or allow adding servers without an admin email.

**Comment by DagAgren** [comment]
That seems to be a Pleroma bug. The email field is not listed as optional in the specs: https://docs.joinmastodon.org/entities/instance/

I can make it optional to work around their bug, but it would be good to report it to them.

**Comment by Flameborn** [comment]
Thank you very much.

Pleroma in its [config cheatsheet](https://docs-develop.pleroma.social/backend/configuration/cheatsheet/) does not mention that any of the *instance* options is required. I think describing why the server was not able to be loaded would be a better solution, instead of allowing it through, since this can happen even to a self-hosted Mastodon server as well.

I am definitely going to raise this with the Pleroma developers, maybe they could add config verification before the server starts.

Thank you very much again.
