### ISSUE TITLE
Theme settings crashing after setting custom tint colour

### ISSUE THREAD

**Issue by ashfurrow** [DagAgren/toot#443]
Here’s what I did:

- Open Settings, Theme. 
- Choose Obsidian and set a custom tint colour (changed both ° and saturation/luminance). 
- Close settings modal. 
- Reopen Settings, go to Theme. 

That’s when the app crashed. Trying to go back in to the Theme settings now makes it crash consistently. 

Switching to another account I had set up, and accessing it’s theme settings, worked fine. Also the crash stopped happening after I did that. 

iPhone 11 Pro, iOS 13.6.1, Toot! v1.13.2 (125), pointing to mastodon.technology. Let me know if I can provide more details!

**Comment by DagAgren** [comment]
Apple crash reports are as usual unreliable, but I see one crash that could possibly be related. I'll investigate that one.

**Comment by DagAgren** [comment]
Judging from that one, though, it shouldn't have anything to do with the colour chosen, but maybe what is on screen at the moment, since it crashes when trying to take a screenshot. Does it still crash if you scroll around a bit first?

**Comment by DagAgren** [comment]
I reproduced the bug. It happens if you open the theme settings with an audio post on the screen.

**Comment by DagAgren** [comment]
Why exactly it's happening is a bit of a mystery, but I put in a workaround for it.

**Comment by ashfurrow** [comment]
Awesome, thank you!
