### ISSUE TITLE
Implement iOS 14 limited photo access

### ISSUE THREAD

**Issue by jrnichols** [DagAgren/toot#446]
I suspect related to new Photos privacy settings in iOS 14. 

* Open app. Go to Toot -> Library.
* Select a couple pics
* .. that's as far as you can get. The sheet is now blank, and all you can do is X.

[This is what you see](https://imgur.com/a/z0G0VL0)

iPhone XR, iOS 14.

**Comment by DagAgren** [comment]
What exactly happens before you see that?

**Comment by jrnichols** [comment]
It brings up the individual photo selector dialogue that’s new to ios14. 

If I go to Settings - Toot! And let it see the whole library, I can add photos. Just not when I choose them individually.

**Comment by DagAgren** [comment]
I guess the limited access mode needs some extra code to work.
