### ISSUE TITLE
Notifications coming in on one device with the content as "🎺"

### ISSUE THREAD

**Issue by VirtualWolf** [DagAgren/toot#448]
I have no idea what's happened, but on my iPhone (11 Pro, iOS 14.0.1, Toot 1.14) all my notifications from Toot no longer show the actual content of the notification but instead look like this:

![IMG_3949](https://user-images.githubusercontent.com/1644623/95029988-ee526c80-06f7-11eb-8cea-8fb4a3391c3b.jpg)

My iPad Pro (11" iPadOS 14.0.1, Toot 1.14) is working as normal. Any ideas on how I might return my notifications to normal? 🙂

**Comment by DagAgren** [comment]
Does logging out and in again help? Or reinstalling the app?

(What this means is that Toot is failing to run the notification extension that decrypts the encrypted content of mastodon notifications, or that it lost the key to decrypt them with. Neither should happen, but apparently sometimes it does?)

**Comment by VirtualWolf** [comment]
No dice I'm afraid. :( I'd already tried logging out of the server I use, but deleting and reinstalling hasn't worked either.

**Comment by DagAgren** [comment]
That is very weird... That definitely shouldn't happen. They seem to work fine for me on mastodon.social at least.

**Comment by DagAgren** [comment]
I've had one other report of this that said it went away with a newer iOS update. Is there one available?

**Comment by VirtualWolf** [comment]
Not yet, I'll see what happens when the next update comes out then!

**Comment by VirtualWolf** [comment]
Huzzah, I just updated to iOS 14.1 and it's all sorted. Cheers!

**Comment by VirtualWolf** [comment]
Interestingly, this has started happening again with the latest Toot update, but like before only on my iPhone. 🤔
