### ISSUE TITLE
Login doesn't work when web domain differs from local domain

### ISSUE THREAD

**Issue by TCFox** [DagAgren/toot#450]
## Issue:
When I add a Mastodon server to Toot!, sometimes the domain for the instance ("`LOCAL_DOMAIN`") differs from the domain used to serve the website ("`WEB_DOMAIN`"). There are several examples of this:

| `LOCAL_DOMAIN` | `WEB_DOMAIN` | Example user |
|-|-|-|
| `tc.nz` | `mastodon.tc.nz` | `me@tc.nz` (https://mastodon.tc.nz/@me) |
| `nitrokey.com` | `social.nitrokey.com` | `nitrokey@nitrokey.com` (https://social.nitrokey.com/@nitrokey) |
| `furry.nz` | `social.furry.nz` | `tequin@furry.nz` (https://social.furry.nz/@tequin) |

* Adding a new server to Toot! with the "local domain" works correctly for public toots, but users are unable to login as the authentication flow goes to the wrong domain. This causes the login to immediately fail. It seems that the login web view is going to https://tc.nz/oauth/authorize?[...] rather than https://mastodon.tc.nz/oauth/authorize?[...].
* If I use the "web domain" instead when adding the server, then Toot! gets confused. Logins work correctly, but all posts are made as if the logged in user is `me@mastodon.tc.nz`, rather than `me@tc.nz`.

Is it possible to resolve this issue? Both methods above make using the app very difficult when used on Mastodon instances that are set up in this way. Happy to supply any additional info you need.

## Reproduction steps:
1. Go to the "Servers" view ("..." > "Servers"), and click "Add Server" at the bottom
1. Search for and add "tc.nz"
1. Note that this has correctly succeeded and toots are visible from the public timeline
1. Go to the "Settings" view ("..." > "Settings") and click "Sign In" under "Identity"
1. Note that this fails, as the OAuth URL is set to `https://tc.nz/oauth/authorize?[...]`, rather than `https://mastodon.tc.nz/oauth/authorize?[...]`

**Comment by DagAgren** [comment]
Fixed this so that logging in after entering LOCAL_DOMAIN will work.

Handling someone entering WEB_DOMAIN instead is kind of tricky, since there doesn't seem to be a way to find the LOCAL_DOMAIN from that, so that still behaves oddly.

**Comment by TCFox** [comment]
Thanks a bunch for resolving this! Chucked you a bit of extra money via the in-app purchase to help support this awesome app 🎉
