### ISSUE TITLE
Weird scrolling behavior of text field while posting new toot

### ISSUE THREAD

**Issue by gesus14** [DagAgren/toot#451]
When I compose a new toot and paste a multi line (approximately 400 characters) text into the text field the cursor moves to the end of the text. The view point/focus is scrolling to the top of the text, not showing the bottom respectively the cursor. 

When I now try to tap somewhere into the text, the cursor should move there. Instead the view point quickly scrolls down and the cursor is placed somewhere else in the last part of the text. 

So it’s not possible to edit the text, which is annoying. 

I would appreciate if this could be fixed. 

Thank you.

**Comment by shahaan1** [comment]
I am experiencing the same issue after update to iOS 14.

The toot composition text input cursor behaviour is erratic. Regardless of where in the text I tap, the cursor does not move to that position. Instead, the cursor jumps to another position several lines up or down. I am not able to see a pattern yet, so cannot comment further.

I have tried all the normal troubleshooting steps including completely uninstalling and reinstalling the app.

This behaviour is isolated to this app. All text input fields in other apps work as expected.

**Comment by DagAgren** [comment]
I can't reproduce this. What app version, iOS version and device is this on?

**Comment by gesus14** [comment]
Thank you. I am using an iPhone SE 2nd edition), iOS 14.2 and toot version 1.14.

**Comment by shahaan1** [comment]
Hello,

I have created a short screen cast video recording of the erratic text cursor movement in the toot composition text entry area.

I am using Toot! v1.14(127) on iOS 14.2 on iPhone 11 Pro.

Link: https://we.tl/t-8gk9Is1Opm

File name is IMG_2927.MP4

Thanks,

Shahaan

**Comment by optikfluffel** [comment]
I have the same issue on an iPhone 8 running Toot! 1.15 on iOS 14.2.

**Comment by satellaviewer** [comment]
I have this issue on a iPhone SE (first version) running Toot v1.15(128) on iOS 14.2. It’s been going since at least the update before the most recent one.

It seems like when there’s a significant amount of lines in the toot text, when I tap on a part of the text to move the cursor there, the cursor position ends up scaled to the space between title bar and top of keyboard. So if I tap at the bottom of that space (just above the top of the keyboard), the cursor actually ends up at the bottom of the toot, instead of where I’d expect it (near the text I tapped).

**Comment by DagAgren** [comment]
Oh, interesting. The reason I could not reproduce this is that it doesn't happen when using the regular keyboard in the simulator (which works like having a hardware keyboard connected), but only happens if you actually type in text on the on-screen keyboard. That will trigger it.

**Comment by DagAgren** [comment]
I think this seems to be an iOS bug. I see some other reports of it online as well for other apps.

It seems that once you start typing with the on-screen keyboard, the OS will now tell your app that the keyboard is appearing after every single keystroke and every single tap in the text area, even if the keyboard is already on screen, and I scroll the text area to the top when the keyboard appears.

I added some code to try and detect these spurious messages, and that seems to have fixed it for me at least. Let me know once the new version is out if there are any further problems!

**Comment by gesus14** [comment]
Thanks for your work, Dag. Unfortunately the problem still exists after upgrading to version 16.0.
