### ISSUE TITLE
App won’t start because of a huge poll

### ISSUE THREAD

**Issue by DysphoricUnicorn** [DagAgren/toot#456]
Yesterday I came across an incredibly long poll with all options being corrupted Unicode characters. While trying to scroll past that the app crashed and now refuses to start.

A partially educated guess would be that the functionality that hides long posts doesn’t trigger for poll options because unmodified mastodon only allows for up to four options and this might cause some kind of overflow.
Obviously I don’t know your code so this could be way off.

iOS version: 14.2
Toot! version: 1.14

**Comment by DagAgren** [comment]
I'll try to fix this by putting in a check to hide polls if they have more than ten options on the timeline.

(They'll still show if you click the toot, so that might still break, but at least you can avoid that.)
