### ISSUE TITLE
Filters not working

### ISSUE THREAD

**Issue by MsCupcake** [DagAgren/toot#461]
Starting a few days ago, the posts containing words and hashtags that I have filtered are showing up on my timeline as if I don't have filters at all. I wasn't sure where this issue was, but I've checked and the posts are still correctly filtered on the web interface.

**Comment by DagAgren** [comment]
This is odd, as nothing should have changed in the code relating to this... Is it still an issue?

**Comment by DagAgren** [comment]
Ooh, I see what happened. Mastodon added a new type of filter and I accidentally didn't future-proof the filter parsing so it chokes.

Fixed now, and hopefully a bit more future proof so it won't happen again.

**Comment by MsCupcake** [comment]
Thank you!
