### ISSUE TITLE
Multi-Option polls display results incorrectly(?)

### ISSUE THREAD

**Issue by gmshh** [DagAgren/toot#462]
On multi-option polls, it seems that results are displayed as the percentage of votes each option has, which is different (and, in my opinion, worse) than mastodon’s behavior in a web browser, where it displays the percentage of people that have chosen each option. The way the app does it leads to rather strange results, especially in longer polls.

**Comment by DagAgren** [comment]
Are you on the latest version? This should be fixed.

**Comment by gmshh** [comment]
Oops, that’s completely my mistake. Updating has fixed the issue.
