### ISSUE TITLE
crashes when playing audio media

### ISSUE THREAD

**Issue by FactorialN** [DagAgren/toot#464]
It's a reproduce-able issue with the built-in audio player. I'm using V1.15(128) with iOS 14.3, and launching the built-in audio player would stably lead to a crash.

**Comment by DagAgren** [comment]
What device is this on?

**Comment by FactorialN** [comment]
> What device is this on?
iPhone 12 Pro Max, iOS 14.3

**Comment by DagAgren** [comment]
A quick test doesn't reproduce it. Do you have a link to a post that crashes for sure?

**Comment by DagAgren** [comment]
I can see a few crashes in the crash reporter. Can't quite figure out how to cause them but added some code to avoid the crash so hopefully that fixes it.
