### ISSUE TITLE
[Feature Request] Boost with comment (quote toot)

### ISSUE THREAD

**Issue by excodex** [DagAgren/toot#465]
Hello,

Is it possible to implement that when the user clicks on boost text an option appears that if he want to boost regularly or with a comment?

When choosing “boosting with comment”, a new toot card appears and the user can write their opinion after followed the link to the toot.

Thank you in advance!

**Comment by DagAgren** [comment]
Mastodon has kind of on purpose avoided implementing a "quote retweet" style function, for social reasons. I don't think I want to go against that.
