### ISSUE TITLE
Custom emoji may be rendered with incorrect aspect ratio

### ISSUE THREAD

**Issue by cpsdqs** [DagAgren/toot#468]
Inline rendering does not appear to preserve the aspect ratio of custom emoji where the original image file has differing width and height.

Example (128×192):
<img width="375" alt="https://icosahedron.website/@halcy/105566640743737360" title="https://icosahedron.website/@halcy/105566640743737360" src="https://user-images.githubusercontent.com/5412095/104819552-7b947980-582e-11eb-8098-36329c3402fb.png">

Reference:
<img width="275" alt="mastofe screenshot" src="https://user-images.githubusercontent.com/5412095/104819729-c367d080-582f-11eb-9f55-8d95a946fd33.png">

**Comment by DagAgren** [comment]
Fixed!
