### ISSUE TITLE
SSO not working

### ISSUE THREAD

**Issue by Jaedotmoe** [DagAgren/toot#469]
I have been notified that the SSO login doesn't work when trying to log into the mastodon.tedomum.net instance.
Any way to fix that?

**Comment by DagAgren** [comment]
It is probably a serverside misconfiguration? I'm not aware of any bugs that would make it not work, bit I recall there being something about keys or certificates or something that needs to be correct for it to work?

**Comment by Jaedotmoe** [comment]
I'm gonna ask the person who reported the bug for a screenshot of it.
I'll update this comment with it.

**Comment by Jaedotmoe** [comment]
Hi!
There is a [small video to show what it does](https://s3.eu-central-1.wasabisys.com/content.jae.moe/FullSizeRender.mov).
Hope it helps.

**Comment by DagAgren** [comment]
I think this is still a bug in the SSO system. If you are not logged in, then even opening the oauth URL in a web browser will not work. After clicking the "LOG IN USING SAML" button, you will always get redirected to the main web UI, not to the completion URL for finishing the oauth login.

**Comment by Jaedotmoe** [comment]
Exactly but what is weird is that it works with other apps like ’Tootle’ without a problem.

**Comment by Jaedotmoe** [comment]
Exactly but what is weird is that it works with other apps like ’Tootle’ without a problem.

**Comment by DagAgren** [comment]
Do you know if it uses the built in framework for authentication? That's the one that pops up a dialog saying the app wants to log in using such and such before showing the login page.
