### ISSUE TITLE
Authentication failure for certain Mastodon instances.

### ISSUE THREAD

**Issue by rtg74** [DagAgren/toot#470]
Hello,

When trying to authenticate to some servers, a 403 forbidden error is shown in the in-app browser.

Toot! Also shows the following error:

The operation couldn't be completed. (com.apple.SafariServices.AuthenticatIon error 1.)

Other IOS Mastodon apps do not encounter this error when authenticating.

**Comment by rtg74** [comment]
Not sure if this helps, but I can get a similar 403 error when attempting to authorize using OAuth.

<img width="950" alt="403 Forbidden" src="https://user-images.githubusercontent.com/77869931/106948605-86398480-66f1-11eb-90f2-1247895cfeac.png">

**Comment by DagAgren** [comment]
This sounds like a server-side issue. I don't think there is anything Toot! can do to fix it.

**Comment by rtg74** [comment]
Thanks.

Other Mastadon apps don’t experience this issue though.

**Comment by DagAgren** [comment]
Do you have an example of a server where this happens that could be used for testing?
