### ISSUE TITLE
Notification change returns 404

### ISSUE THREAD

**Issue by pixel8383** [DagAgren/toot#471]
Since a few weeks I was not receiving anymore the notifications from the instance on my iOS app. I tried to remove/install back again the app with no success.

Today I tried to go into _Settings -> Notifications_ inside the app but when I try to switch off/on any of the notification types available I get: "`Failed to change notification settings - Server did not return an OK response code (404)`".

What should I do in order to check that everything is fine on server side? My instance seems to be running fine with no errors.

Thank you.

**Comment by DagAgren** [comment]
Weird. Logging out and in again usually fixes any notification weirdness, though?

**Comment by pixel8383** [comment]
I just tried to logout/login and I am able to change those settings now but I don't get to receive any notification on my iPhone (iOS 14.4). System notifications for the app are enabled. Is there anyway to register once again the app to the iOS notification system?

**Comment by DagAgren** [comment]
I think that may have been because the notification relay was down. It should be back now.

**Comment by pixel8383** [comment]
What do you mean? I am still facing the issue: my notifications from Toot! are not sent to the iOS Notification Center (they are enabled both in the app and on the iOS Settings).

**Comment by DagAgren** [comment]
Can you try logging out and in again once more now that the relay is back up and running?

**Comment by pixel8383** [comment]
I tried and waited for a notification but nothing changed: I get an answer on mastodon but no notification of it on my iPhone.
