### ISSUE TITLE
Missing App Privacy practices on the App Store

### ISSUE THREAD

**Issue by dminca** [DagAgren/toot#472]
Wanted to download the app as the UI/UX seems quite appealing, but having seen the Privacy details are missing I thought you're no longer supporting the application anymore.

<img width="540" alt="image" src="https://user-images.githubusercontent.com/5355219/106358152-970d8300-630a-11eb-9c8a-e7a390dab261.png">

Is it in your plan to update this soon?

**Comment by DagAgren** [comment]
I'm pretty sure I did update that already? Weird.

No data is collected by Toot, is what it would say.

**Comment by mmahmoudian** [comment]
I'm having hard time convincing some friends to use toot! Just because of this reason.

**Comment by DagAgren** [comment]
This is weird, this is how it looks for me in the app store settings:

<img width="625" alt="Screenshot 2021-02-20 at 14 28 42" src="https://user-images.githubusercontent.com/11536828/108595325-fc8fe500-7387-11eb-89df-963dc44609f0.png">

It might be it doesn't go live until I push out a new version? Working on one now but it'll be a little while yet before it's ready to go out.

**Comment by mmahmoudian** [comment]
This is what I see literally now:

![image](https://user-images.githubusercontent.com/390889/108595633-a7ed6980-7389-11eb-96d5-aea47a0eb9ff.png)

**Comment by DagAgren** [comment]
Maybe I'll try pushing out a version with a few bug fixes and see if updates.

**Comment by DagAgren** [comment]
There was "Publish" button at the top of the page that I didn't see.

🤦 

It's published now, and that bugfix build will be coming soon, as I only noticed this while actually submitting that build for review.

**Comment by mmahmoudian** [comment]
@DagAgren Thanks for taking the action so quickly.
