### ISSUE TITLE
Editing earlier part of a text is impossible

### ISSUE THREAD

**Issue by mmahmoudian** [DagAgren/toot#475]
When creating a new toot, if user wants to edit the earlier part of the draft, it is impossible to scroll back and tap on the desired location to move the cursor there. I recorded a short video to showcase this:

https://www.dropbox.com/s/1dnygtla8w3shbv/RPReplay_Final1613811950.MP4?dl=0

**Comment by DagAgren** [comment]
Is this the same issue as https://github.com/DagAgren/toot/issues/451 ?

**Comment by mmahmoudian** [comment]
@DagAgren almost. There are two issues that the #451 bundled them together but imho they are separate bugs. One of them is related to pasting, which the cursor goes behind the keyboard and not visible to user. This is something that I haven't invested time to find a deterministic approach to reproduce it but I have faced it.

The second bug which #451 briefly touched upon is the bug that I demonstrated.

**Comment by DagAgren** [comment]
Looks like I have a fix for this.
