### ISSUE TITLE
Official account button in settings just shows error alert

### ISSUE THREAD

**Issue by lilyball** [DagAgren/toot#479]
The “Official account for Toot!” button is broken at the moment. What I expected it to do was to push on a profile view for the account, showing any appropriate loading within the profile page, and loading it via my active server. Instead it shows an activity bezel, followed by an error alert that says

> **Failed to use remote server**
> Server did not return an OK response code (500)

This is a very generic error. I can’t tell what server it’s trying to talk to, and even worse, I can’t even learn from this what the official account is.

![9776798E-28C0-4AB5-94A6-C9DF897BFD82](https://user-images.githubusercontent.com/714/109445951-95140e00-79f5-11eb-98a0-a64c200c3677.jpeg)

**Comment by DagAgren** [comment]
This just means mastodon.social is down. It seems to work fine now.

**Comment by lilyball** [comment]
I'm glad the error was temporary, but I still expected better behavior here. I couldn't even tell what the official account name was because of this error. If pushing on a profile view for this and doing the loading there is too complicated, then at least offer me a "Show on Web" button that opens it in Safari.

**Comment by lilyball** [comment]
I tried again just now and got the exact same error. mastodon.social is up and running so I can't tell what's going on.
