### ISSUE TITLE
Profile metadata only shows 4 entries

### ISSUE THREAD

**Issue by lilyball** [DagAgren/toot#483]
When viewing a profile in Toot! only 4 metadata entries are shown, without any indication that there are more. Perhaps vanilla Mastodon only allows 4? I don’t know. But my server allows 10 instead, and it’s really confusing to have up to 6 metadata entries simply missing.

**Comment by DagAgren** [comment]
Yes, regular Mastodon only allows 4. The way this is currently implemented makes it a huge pain to add more of these, so I don't think this will be fixed for now.

**Comment by lilyball** [comment]
Can you at least detect when there's more and add a "Show more" link that opens the web page then? The fact that I can't even tell that there are missing entries makes me distrust the app's profile display.
