### ISSUE TITLE
Ampersand truncates image descriptions

### ISSUE THREAD

**Issue by nfagerlund** [DagAgren/toot#49]
If you use the `&` character in an image description, it deletes any text that follows it.

**Comment by DagAgren** [comment]
Does it work on web? Using &, and viewing &?

**Comment by nfagerlund** [comment]
Yeah. Writing/reading `&` in descriptions works on both the default web interface and on Pinafore.

**Comment by DagAgren** [comment]
What about & written in Toot and read on the web, and vice versa?

**Comment by nfagerlund** [comment]
When I use & in a description from Toot, the result is the same in all clients: the & and all following text in that description are absent. (Though on some clients you need to view it as a tooltip or whatever.)

Here's an affected toot, for reference: https://mastodon.social/@nfagerlund/99915523609575670

Also, I haven't tested this across instances, only on m.s where my one account is.

**Comment by DagAgren** [comment]
All right, I think I tracked down the problem: `URLComponents.query` is broken and useless (it returns the query without escaping, but also with & separators, so, uh...?)

https://developer.apple.com/documentation/foundation/urlcomponents/1780254-query

Will implement it slightly differently, avoiding that function.

**Comment by DagAgren** [comment]
There: https://icosahedron.website/@WAHa_06x36/100312251037679360

**Comment by nfagerlund** [comment]
🙌🏼
