### ISSUE TITLE
[Suggestion] Democratize the "awful servers" list

### ISSUE THREAD

**Issue by mcgroarty** [DagAgren/toot#492]
Presently, Toot! has a very small list of "awful servers."

Having the app author manage this list puts the author in a difficult position of having to decide what speech is "awful."

Instead of managing your own list, consider offering a field where users can provide a URL that serves a json list of "awful" domains. There are a few sites that manage block lists, and you could have radio checkboxes next to a couple of those if they're willing to work with you. Additionally, the user could point to a source they prefer using the URL field, or they could opt out of filtering.

To control load, it's likely not necessary to update the list more than once a day, although you could include a refresh button to help people who are developing and testing "awful" lists.

**Comment by Nephilimi** [comment]
First steps a user managed list seems not too terrible to impliment. An off switch is also highly desirable. Neither really go along with the theme of easy to use which is what attracted me to the app. 

I'd also like to see some sort of policy on the censorship supported by the app, it's not often you see such a statement first line in the app description and that got me curious how much else is going to be hidden from me. I got the impression Mastodon was built decentralized to stop de-platforming among other things. I'd rather see these decisions in the hands of the user.

**Comment by Nephilimi** [comment]
OR is this a misunderstanding on my part, not about censorship but a problem with platform compatibility and the Toot! app? Gab is some sort of fork of mastodon and spinster is something called soapbox. 
I'm having trouble adding gitmo.life to the Toot! app and it is something called Misskey.
In other words is Toot! only compatible with tootsuite/mastodon servers and not the other federated servers?

**Comment by mjgardner** [comment]
It's within @DagAgren 's rights to restrict the app however they like.

But I came to the fediverse to escape a pre-filtered network, and it's within my right to withhold my $3.99.
