### ISSUE TITLE
Doesn’t recognize my PRO account on mobile app

### ISSUE THREAD

**Issue by TinaGerow** [DagAgren/toot#496]
When I try to toot from the Toot app it tells me I need a PRO account and tries to get me to upgrade but I already have a PRO account. It’s been quite a while since I’ve used the app but it used to let me toot just fine. Not sure what changed.

**Comment by DagAgren** [comment]
I don't really know what a pro account is?

**Comment by TinaGerow** [comment]
You pay extra each month for extra functionality = PRO account which enables you to be able to also use a 3rd party app to Toot etc. But when I try to login on the app it says I have to upgrade to a PRO account and to submit a ticket if there’s an issue. So, here I am, submitting a ticket.

**Comment by DagAgren** [comment]
This sounds like it is entirely an issue with whatever site it is you are using, and I don't know which one that is?

**Comment by TinaGerow** [comment]
I was trying to log into the Toot app and that’s the one telling me I need a pro account through Counter Social.

Tina Gerow
~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~
Sexy, Snarky, Sensuous
tinagerow.com
cassieryan.com
- Sleeping With Shadows - written as Cassie Ryan
 - Club Desire: My Addiction – written as Cassie Ryan
- Into a Dangerous Mind – written as Tina Gerow

**Comment by DagAgren** [comment]
Pro accounts are a counter.social thing, not a Mastodon feature or anything Toot knows about. You need to contact your admins if you have a problem with it.
