### ISSUE TITLE
“Reply”, “Boost”, and “Favourite”: replace texts with glyphs, and option to show count

### ISSUE THREAD

**Issue by ShredderWalnut** [DagAgren/toot#509]
Hello,

IMHO, it’s redundant to show the “REPLY”, “BOOST”, and “FAVOURITE” buttons as text buttons under every toot. Personally, I would prefer glyphs for less UI clutter and better readability.

A separate but related request is the option to show the numbers next to the three glyphs. I am aware that many prefer to *not* see the numbers, but when scrolling through the timeline, I heavily rely on this feature to easily tell at a glance which posts are garnering interactions without having to click on the toot to see its details.

Thank you for this delightful app!

**Comment by DagAgren** [comment]
This is an intentional design choice. I honestly think having text that describes actions is a lot more usable and mystery icons.
