### ISSUE TITLE
Dynamic type not supported.

### ISSUE THREAD

**Issue by rkingett** [DagAgren/toot#523]
The app appears to not support dynamic type on iOS. [Dynamic type is an accessibility feature many people use, even without a visual disability.](https://developer.apple.com/documentation/uikit/uifont/scaling_fonts_automatically)

Sighted users are reporting the app does not support dynamic type on Mastodon. [Here's Apple's documentation for developers on scaling text automatically.](https://developer.apple.com/documentation/uikit/uifont/scaling_fonts_automatically)

I am totally blind so am unable to test this, myself.

**Comment by rbruchal** [comment]
+1 for this. Everyone will eventually need dynamic type - it's just a normal part of aging. 😀

**Comment by rbruchal** [comment]
This might be a duplicate of #99

**Comment by rkingett** [comment]
Yeah, my bad. I couldn't find it in the search bar so I created one. Yeah, it is a duplicate of [this issue, 99.](https://github.com/DagAgren/toot/issues/99)
