### ISSUE TITLE
Scrolling to top sometimes fails

### ISSUE THREAD

**Issue by DagAgren** [DagAgren/toot#53]
This may be related to autolayout not working well in UITableView?

**Comment by moritzheiber** [comment]
Leaving this here: https://mastodon.social/@eurasierboy/100594040616120681

Maybe you want to collaborate on this with John?

**Comment by DagAgren** [comment]
I *think* I have fixed this now, so I am closing the issue, but do post here immediately if you see it happening again after the next release!

**Comment by moritzheiber** [comment]
I can confirm, the latest beta fixes this 😊🎉
