### ISSUE TITLE
Has Toot been abandoned?

### ISSUE THREAD

**Issue by kevquirk** [DagAgren/toot#531]
No updates to the app in over a year and a developer that's MIA. Is this project abandoned, @DagAgren ?

I see activity from you on other projects just 23 days ago, so you're still around.

Please, just let us know so we can make a decision either way as to whether we need to look for another client. Toot is stagnating and falling behind the curve as more features are introduced into Mastodon.

Thanks,

Kev

**Comment by DagAgren** [comment]
I guess the current status is "on hiatus", since I've been finding it hard to find time for it lately. Haven't made a final decision about how to proceed with it yet.

**Comment by kevquirk** [comment]
Thanks for replying. I get it - it's hard to find the time for side projects some times. I for one would love to see Toot continue - it's by far the best client out there.

Have you thought about asking the community for help with it?

**Comment by alfredo87** [comment]
So, Toot is being let to rest without much ado? Just a comment: if users pay they deserve some support by developer. Most payments are “for further development”. May I suggest you go and ask for help… thanks for creating toot, don’t let it die

**Comment by marc0janssen** [comment]
I like to add nu 5 cent too. Love this app for a long time now. Hope this will continue. If donation is appreciated to continue I am happy to

**Comment by lucascantor** [comment]
Personally, I'd be more than happy to pay for a recurring in-app subscription to keep the app alive ❤️

**Comment by VirtualWolf** [comment]
> Personally, I'd be more than happy to pay for a recurring in-app subscription to keep the app alive ❤️

Definitely agreed, I'm already chipping in a couple of dollars a month for the hosting costs of the server I'm on, seems only reasonable to do the same for the client I use to access it. :)

**Comment by masto** [comment]
Toot! is currently the #1 paid iPhone app in the Social Networking category on the App Store, and #2 for iPad. (I wonder if there are some recent events that might have spurred that…)

I’m hoping that provides some motivation to pick the project back up, or maybe hand it off. I’ve literally only been using it for 5 minutes, and the UX is fabulous, but things like the share button instantly crashing mean I have to go back to a more stable client. I assumed from its popularity that it was actively supported, and I guess that’s on me. I’m not going to demand a refund or anything, but I have my fingers crossed that at least a bugfix release will appear soon.

**Comment by GthSd** [comment]
I also sincerely hope the influx of users on the fediverse and probably also for Toot! might rekindle development. It’s a great app and the ability to add local timelines from other instances without needing an account on each one, is gold.

**Comment by jasontucker** [comment]
With so many new featured being added to Mastodon I'd love to see these featured being added to Toot! and even if they were available only behind a paywall in the app I'd be all for paying for the development of these features.

**Comment by chartier** [comment]
@DagAgren It seems like Mastodon is seeing a _real_ explosion this time. Massive growth, front pages of all the major news outlets, and even Musk has started shitposting about it since it's making a dent in Twitter. Lol. Feels like there's real momentum here.

If you can find the time, I think now would be perfect to dust off Toot development. Toot is a good app with unique features that the community clearly wants (especially browsing and interacting with other instances, which is prohibitively difficult with most other apps). Either way thanks for listening.

**Comment by Sarahlizzy** [comment]
This is absolutely the best Mastodon client around. Really hope it prospers in future. Thanks for all you've done to this point. Love your work.

**Comment by anarchimedes** [comment]
i believe that if there was a tiny little update to show up, just to change the "1 year ago" label in AppStore, you could go with the flow of recent peaks and get even more donuts.

**Comment by DagAgren** [comment]
Yeah, this explosions has changed the situation somewhat. I am trying to figure out if I could get some time to work on some maintenance releases at least.

**Comment by kevquirk** [comment]
That's fantastic new, thanks @DagAgren - hope you can make it work!

**Comment by jmichaelward** [comment]
Just wanted to add to the praise for this terrific client and hope the changing landscape can provide inspiration for continued development support. Please let the community know if there’s anything we can do to contribute, either directly via code or financially via GitHub, Patreon, or other channels.

**Comment by chandra-sekar** [comment]
@DagAgren Thank you so much for your work on the app. It is by far my favorite client to use Mastodon from.

**Comment by leporine** [comment]
This is so encouraging! I'd really like to see Toot! given some more love, eg styled text support, and the accommodation for the new toot editing facility, where supported. Toot! remains my usual client on the iPad - here's hoping it becomes even better!

**Comment by sleepyfran** [comment]
@DagAgren any chance of releasing the source code of Toot! in case you decide to put it on maintenance mode? I honestly find it the best Mastodon client for iOS. It's such a joy to use and it'd be so sad to not see it grow with Mastodon!

**Comment by Letterus** [comment]
@DagAgren Yes. I have to support all of my ancestors. Toot! is by far the best Mastodon app out there and I'm willing to contribute. Either by submitting some lines of code or by throwing bucks of money on you. Let us know!

**Comment by RockinKat** [comment]
Hi @DagAgren  really glad to hear this.

just a question, but is there any particular reason you haven’t toggled it in the App Store to allow Toot! To be installed on ARM based Macs? I’ve got the iOS Metatext app installed on my Mac but I’d really love to put Toot! On it instead.

**Comment by supernovae** [comment]
I love toot - would love to see updates even if minor (search is a bit confusing / broken right now)

**Comment by supernovae** [comment]
I see your #1 in the pad app category for social media - quite the feat! :)

**Comment by TheQuinbox** [comment]
I think this can be closed now, seeing the recent announcement about updates :)

**Comment by PatriciaW43** [comment]
I can't use Toot on my iPad at all. I have wasted my money. It will not verify my signon
![73C6EA04-061A-4C79-9292-46CE023802BC](https://user-images.githubusercontent.com/5775482/204010278-e8501a52-f963-401a-a59a-cd7c371f7e8d.png)

**Comment by kevquirk** [comment]
@PatriciaW43 hijacking a thread with something completely unrelated is considered bad form.

A quick look online and it seems that mstdn.ca is offline. So either you typo'd the name, or the server is offline. Either way, this isn't a Toot! issue.

https://downforeveryoneorjustme.com/mstdn.ca

**Comment by PatriciaW43** [comment]
One other server I attempted to sign on to is online now but I can't sign onto now is climatejustice.social.

**Comment by PatriciaW43** [comment]
﻿I don't understand why my post was considered to hijack the thread. I bought toot! about a week ago and haven't been able to use it. I went to GitHub to post this and then saw this question about toot possibly being abandoned and felt it might not be worthwhile creating a new thread if this is the case. 

By the way when I was trying to find a solution to this I came across a suggestion that using 2fa might be an issue.  I have 2fa on. 

Patricia
***@***.***

be kind, be calm and be safe

**Comment by mundschenk-at** [comment]
> I don't understand why my post was considered to hijack the thread.

Because this issue is not about your issue. Open a new one.

**Comment by kevquirk** [comment]
> Mstdn.ca wasn't off line earlier...So I still consider this to be a Toot problem.

Just because you consider an issue to be something, doesn't mean it is. I just checked again and Mastdn.ca is *still* down. Plus the fact that thousands of other people are happily using Toot, I'd say the problem here is with the server, not Toot.

Anyway, like @mundschenk-at said, if you still think it's a Toot problem, open a fresh issue for your specific problem. I imagine the reply will be the same as mine is though...

**Comment by PatriciaW43** [comment]
﻿I know this is not a toot problem but seems to be a mastodon problem. I  tried to sign on to climatejustice.ca but for some reason it doesn't let me sign on so I requested a new password but I never got the email. 
I have applied for a new account. 

Patricia
***@***.***

be kind, be calm and be safe
