### ISSUE TITLE
Can’t dismiss screenshot text helper

### ISSUE THREAD

**Issue by bgreenlee** [DagAgren/toot#535]
This is not a great user experience, with no way to hide the redundant screenshot text helper:

![173DCBCC-315C-4678-B04F-B5339F3916DE](https://user-images.githubusercontent.com/2901/200149231-4cace559-deb3-4e0b-a410-138a3908df97.png)

**Comment by ephemeraleternity** [comment]
You can tap on the text inside the black box to hide it.

**Comment by bgreenlee** [comment]
So you can. I thought I tried that. Sorry!
