### ISSUE TITLE
Feature request: Unread Count and jump to last read post

### ISSUE THREAD

**Issue by jayv** [DagAgren/toot#569]
Overall I'm pretty happy with Toot, here are some missing features that would turn the app into a solid 5/5 and are the main features that convinced me to pay for Twitterific app.

Currently Toot displays "see latest updates" but it's not really that helpful, it would be nice to have a counter for number of posts queued up above the scroll position [(eg Twitterific has this in top right](https://bddf794624247cea6a0b-b4761d2ba0154d0278c36dbf2b3c114d.ssl.cf1.rackcdn.com/untitled-151507632535430.png)) to have an idea of how where you are. 

In addition to that I often accidentally hit the home button which scrolls all the way to the top and then I end up manually scrolling all the way down hunting for where I left off (100s of posts). Twitterific has a handy jump to last read post function feature, I believe they implement this by tracking when a scroll position remains stable for  more than `n` seconds, even if it's not perfect it's often very close which avoids the frustration.

**Comment by jayv** [comment]
I just noticed that my 2nd request was suggested earlier: https://github.com/DagAgren/toot/issues/229

**Comment by metavida** [comment]
I love this feature in Tweetbot. As a reader it lets me adjust my reading pace depending on how much time I have and how much is available to read. (Only a few dozen new posts? I might click through and read longer articles. Hundreds unread & limited reading time? I’ll do much more skimming & keep an eye for my favorite posters.)

I realize that with the Mastodon “read/load more” feature it may not be possible to show a count of **all** remaining posts, but even showing a count like “50+” would be helpful to set my reading pace. 

Here’s what the counter (upper right) looks like in Tweetbot: 
![A screenshot of the iOS Tweetbot app with the “number of unread tweets” count visible](https://user-images.githubusercontent.com/1933/204104718-e0321a1e-b0eb-4057-aaba-86e60a1f6281.jpeg)

**Comment by alexbayleaf** [comment]
This might be asking a bit much but I’d love to see this “last unread” also shared across devices, so that if I switch from my iPad to phone it knows where I last was.

**Comment by DagAgren** [comment]
It is not really technically possible to get an accurate unread count, unfortunately.
