### ISSUE TITLE
Alt-text overlay transparency makes the text illegible if it is overlaid on a text screenshot (see attached image)

### ISSUE THREAD

**Issue by jayholller** [DagAgren/toot#577]
![IMG_2717](https://user-images.githubusercontent.com/25752097/204097692-3fb7e708-db6f-46c4-b7ad-810443321b15.PNG)

**Comment by VirtualWolf** [comment]
Tap on the alt text box and it'll go away. 🙂

**Comment by jayholller** [comment]
Sure but I’d rather read the text in that modal view. On Nov 26, 2022, at 4:40 PM, VirtualWolf ***@***.***> wrote:﻿
Tap on the alt text box and it'll go away. 🙂

**Comment by DagAgren** [comment]
Too obscure an issue to have time to work on for the forseeable future.
