### ISSUE TITLE
Keyboard bindings for common actions

### ISSUE THREAD

**Issue by alexbayleaf** [DagAgren/toot#581]
I use an iPad Pro with an external keyboard. I would love to see some keyboard bindings for common actions. A good example of a similar implementation is the [Tweetbot keyboard shortcuts](https://shortcuts.fm/tweetbot/).

The ones I find myself wanting to use most often are “new toot” and some keyboard way to go into and out of toot details/threads, which is currently done by tapping/swiping.

**Comment by DagAgren** [comment]
Duplicate issue.
