### ISSUE TITLE
Also allow swipe to open toot

### ISSUE THREAD

**Issue by alexbayleaf** [DagAgren/toot#582]
At present to open a toot in a more detailed view/show the thread/etc, you tap on it. Then to go back you swipe right to return to the timeline. For symmetry, it would be good to allow the user to swipe left to view a toot. This means that if you are going back and forth a lot, the gestures will be more intuitive. There’s probably no need to remove the current behaviour — this could be in addition.

**Comment by DagAgren** [comment]
This is very unconventional UI, so not going to implement it.
