### ISSUE TITLE
Show usage histogram in list of pinned tags

### ISSUE THREAD

**Issue by alexbayleaf** [DagAgren/toot#584]
When you search for a tag on the global timeline, you can see a histogram of how popular it’s been lately, so you can usefully pick the most active tag. Since that histogram’s being produced anyway, it would be extremely useful if it showed up next to the tag name among your pinned tags. 

Red circles in attached pics show where I’d put them.

![DBB9911F-A9A0-4FDE-A765-1598DC7A61CE](https://user-images.githubusercontent.com/30330308/204122232-e24d3993-fda4-4caa-8f89-6c4ee6b01b90.jpeg)
![0525421D-B2FE-4D60-AA21-AC7E50D20AFF](https://user-images.githubusercontent.com/30330308/204122237-491fa146-6122-4c85-ab8d-fc7ad28b6dbc.jpeg)

**Comment by DagAgren** [comment]
That data is not available except in search results.
