### ISSUE TITLE
Error while viewing any animated gif/video: "Failed to load audio. The server is not correctly configured"

### ISSUE THREAD

**Issue by elegansen** [DagAgren/toot#585]
Hi, first things first: excellent app! Best one for Mastodon out there, hands down.

I have problems viewing any kind of animated gifs in the app. The gifs are frozen images in my view, no matter which person who uploaded it. 

When I try to tap a gif I get the following error message: 
![99f59e4376c21c24](https://user-images.githubusercontent.com/118933058/204135615-7db4e536-9edd-4824-95ea-8b17441f0364.png)

"Failed to load audio. The server is not correctly configured". To my knowledge these images do not even contain audio. 
Although they are gifs from the start, when you upload these images to mastodon instances they seem to be converted to mp4 files? (because that's the file format of the file if you rightclick and pick "Save Images As..") 

Had no problems with this when using Metatext prior to the installation of Toot!. But since I installed Toot I can't even play gifs or videos from other users I don't even follow. 

Very strange. What is the configuration that needs to be done to my server? (auto-play gifs are turned on in the web browser, from which I have no problems with viewing gifs)

**Comment by DagAgren** [comment]
Probably sending incorrect MIME types for files? Not really related to Toot, though.
