### ISSUE TITLE
Lists

### ISSUE THREAD

**Issue by DagAgren** [DagAgren/toot#6]
The home screen should have support for selecting and creating lists.

**Comment by ckolderup** [comment]
It would be great if it would remember the list you had selected across launches of the app (even if the app gets unloaded from memory)-- I really loved this feature of Tweetbot, letting me have a smaller list as my "default timeline"

**Comment by ausfestivus** [comment]
It would be really useful if I could add an account to a list from the accounts profile page.
When viewing a profile, clock the "More..." button. Select "Manage Lists" or something like that.
