### ISSUE TITLE
.gifs does not play 

### ISSUE THREAD

**Issue by KurzGedanke** [DagAgren/toot#66]
- Phone: iPhone X, 64gb
- OS: 11.4.1
- toot! version: 1.0 (23)
- Instance: Chaos.Social

I tried to play .gifs but it doesn't load and there is only a loading cycle. Till now every single does not work.

Example .gif:
https://niu.moe/@SarcasmKid/100397072196945194

**Comment by DagAgren** [comment]
See https://github.com/DagAgren/toot/issues/7
