### ISSUE TITLE
.mp4 does not load.

### ISSUE THREAD

**Issue by KurzGedanke** [DagAgren/toot#67]
- Phone: iPhone X, 64gb
- OS: 11.4.1
- toot! version: 1.0 (23)
- Instance: Chaos.Social

The same like .gifs but this time with .mp4 content. A thumbnail is loaded, but I won't play. No loading indicator. 

Example: https://chaos.social/@kurzgedanke/100396959988529959

**Comment by DagAgren** [comment]
See 
https://github.com/DagAgren/toot/issues/8
