### ISSUE TITLE
Doubled push notifications

### ISSUE THREAD

**Issue by nfagerlund** [DagAgren/toot#71]
(I don't have a clean repro for this, but I'm willing to work with you if you have any ideas.)

After restarting my phone, Toot lost my instance auth somehow. That isn't the bug (Tweetbot did the same thing, so something external was up). The bug is, now I get two copies of every push notification. 

also: Before I signed in again, push notifications had text like "couldn't decode" or something.

**Comment by DagAgren** [comment]
Hmm, I think there's nothing I can do in that case. You have to go and disable the authentication in the web UI.

**Comment by moonmilk** [comment]
Same thing just happened to me. I restarted my phone, had to reauthenticate in both my instances (but I didn't have to log in again). Now I'm getting two notifications per event. I'm using v1.2(53).

**Comment by moonmilk** [comment]
If i understand your comment correctly, the fix is to go into Your Authorized Applications in the web UI and deauthorize all but one copy of Toot! I am in fact seeing three (!) Toots in my Authorized Applications, so i'll go kill two of them.
