### ISSUE TITLE
Long pressing links on iPad causes the app to crash

### ISSUE THREAD

**Issue by timonus** [DagAgren/toot#72]
Likely due to missing `popoverPresentationController` configuration that’s required on iPad. Video: https://www.dropbox.com/s/rttvov8uahlukco/

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DagAgren** [comment]
See https://github.com/DagAgren/toot/issues/69

**Comment by timonus** [comment]
nice.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
