### ISSUE TITLE
Failed to load instace data

### ISSUE THREAD

**Issue by rizwankce** [DagAgren/toot#73]
When trying to add instance at first launch. Getting an error popup says 

"Failed to load instance data" - "An SSL error has occurred and a secure connection to the server cannot be made"

Maybe it is because mastodon is blocked my ISP's here in China. However, it should be working when i have VPN or Proxy enabled.

**Comment by DagAgren** [comment]
Something is preventing SSL from working, not sure what it would be though... Does it work through the browser? Or tools like curl?

**Comment by rizwankce** [comment]
Works fine on browser. Haven't tried looking into api endpoints yet. But it was working fine when I changed my vpn settings to send all traffic to proxy. So might be issues with vpn app being in middle. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
