### ISSUE TITLE
Uncluttered Timeline

### ISSUE THREAD

**Issue by paviro** [DagAgren/toot#76]
I think it would make sense not to show the boost, favorite action buttons on every twoot since it clutteres the timeline and people won’t need them for every toot. Maybe only display them after pressing the twoot and add a swipe gesture for the twoot detail view now opened on touchdown. 
See Tweetbot for an example what I mean.

**Comment by VioletPixel** [comment]
This would be nice, but I'd prefer an option to replace these words with icons instead.
