### ISSUE TITLE
Profile Description

### ISSUE THREAD

**Issue by paviro** [DagAgren/toot#77]
The profile description is currently not completely readable. It should have more space. Also is it possible to show the custom fields? 
![db53f25c-ba79-41f9-8789-245d455f1e52](https://user-images.githubusercontent.com/992826/44015081-91b25180-9ecf-11e8-864e-5dac33514a0c.png)

**Comment by DagAgren** [comment]
Weird, it is used to be sized correctly. Will have to investigate.
