### ISSUE TITLE
Support for Open Graph previews for external links

### ISSUE THREAD

**Issue by m4p** [DagAgren/toot#78]
I think it would be great if Toot! could parse external links in posts and add a open graph based preview like many modern clients (including Twitter) do. (There's an open source component that could be used/augmented at https://github.com/marty-suzuki/URLEmbeddedView) In my opinion this would further increase the polish and smoothness of the app. I took the freedom to mock up two examples:

![after2](https://user-images.githubusercontent.com/666042/44018595-8f3ec4e4-9edc-11e8-92ad-5397a9ef03b2.jpg)
![after1](https://user-images.githubusercontent.com/666042/44018599-91f5dcf4-9edc-11e8-9592-84a20f6f24cb.jpg)

**Comment by DagAgren** [comment]
Well, Mastodon provides similar data, which is used when opening up the toot, but it requires one network access per toot shown to load, and will eat up the rate limiting pretty quick. It also causes asynchronous resizes of the toot sizes, which could get very annoying very quickly.

Using OpenGraph would deal with the rate limiting, and could mean we know if there is going to be more data, and put in placeholder to avoid resizes, but it would also mean it might be inconsistent with what is shown after you open the toot, which isn't great either.

**Comment by DagAgren** [comment]
I think for now I won't be doing this.

**Comment by DagAgren** [comment]
Update: Since Mastodon added this data to all statuses, it is now implemented using that: https://github.com/DagAgren/toot/issues/216
