### ISSUE TITLE
Inverted ‘Following/ Followed by’ titles on personal account

### ISSUE THREAD

**Issue by jc-f** [DagAgren/toot#79]
Going to my personal account and tapping on “Following” will bring the list of accounts that I follow, but has the incorrect title and says “Followed by”. Same things happens with the “Followed by” list.

**Comment by DagAgren** [comment]
No, unfortunately, those titles are correct. Tapping "Following" will take you to a list of accounts that are "Followed by you". The language for this is a real mess to try and get right.

**Comment by jc-f** [comment]
Ok got it. Problem was I didn’t have a display name. It uses the string “Followed by [Display name]” so if there isn’t a display name it becomes ambiguous.

**Comment by DagAgren** [comment]
Ah. Might be worth putting in a "you" there instead of the name, perhaps.
