### ISSUE TITLE
Default post privacy

### ISSUE THREAD

**Issue by cangyuyao** [DagAgren/toot#82]
Similar to the option in Settings > Preferences.

**Comment by paviro** [comment]
Also please add a default privacy for replies. I would love to automatically post all my toots public but replies unlisted for example :)

**Comment by DagAgren** [comment]
This could be part of https://github.com/DagAgren/toot/issues/169.

**Comment by Canorus** [comment]
Ideally it could be done by just retrieving from account identity when registering account/starting application which will sync to web automatically, but also could be achieved by putting relevant settings under Settings > Identity etc. as suggested I suppose.

**Comment by mistydemeo** [comment]
This is the biggest thing I miss from other clients; I’d love to see this make it into Toot!
