### ISSUE TITLE
Deal with wide gamut images

### ISSUE THREAD

**Issue by cangyuyao** [DagAgren/toot#84]
It's really strange that I've tried dozens of mastodon iOS clients and none of them considers wide gamut images uploading. I'm using iPhone 8, and all the photos and screenshots lose their saturation after upload. I'm not quite clear on how color profiles work but this is probably because the color profile of the image is simply discarded when upload.

**Comment by DagAgren** [comment]
Not really a Toot! bug, it's probably the Mastodon server side that processes the image. You should try it with the web UI, and report it to the Mastodon project if it doesn't work there either.

**Comment by cangyuyao** [comment]
It's not a Mastodon's problem. I tried uploading on the web (with Safari) and the results are all right.

**Comment by DagAgren** [comment]
Could you send me some images that show the problem?

**Comment by cangyuyao** [comment]
Download the original photo here: https://photos.app.goo.gl/J89sJgDz6PN488L16
(Google also has this issues on thumbnails for web viewing, but the original file is intact.)

Here is a comparison: https://pawoo.net/@lanee/100560759897209976

**Comment by DagAgren** [comment]
I think this is fixed?

**Comment by cangyuyao** [comment]
> I think this is fixed?

No, it’s not. 

Even worse if you post image through share extension in iOS12, iOS fixes the colour for you. But in iOS13 this function is removed.
