### ISSUE TITLE
[UI] Empty space on error message

### ISSUE THREAD

**Issue by seik** [DagAgren/toot#85]
The alert of error when the feed cannot be updated shows an empty space after clicking on it. In theory there should be a error there.

Reference: https://mastodon.social/@seik/100560016429565939

![imagen](https://user-images.githubusercontent.com/9640279/44210603-38b6af00-a167-11e8-943d-d93e7b0d0b3f.png)

**Comment by DagAgren** [comment]
Apparently this happens in airplane mode?

**Comment by seik** [comment]
@DagAgren Yes, my guess is, from what you have said, there should be a error message but since this error is due to not having internet the app cannot fetch any error? I don't know, just guessing.

**Comment by DagAgren** [comment]
I wanted to try fixing this, and I tried it once and I could reproduce it, but then never again. Each time the error message showed up as it should.

The box even resizes to the right size as if the message was there, it's just invisible. I'll have to leave this for now until I get a better idea.
