### ISSUE TITLE
Reduce entry friction

### ISSUE THREAD

**Issue by faissaloo** [DagAgren/toot#87]
Atm the problem with most fedi stuff is that it tries to push the idea of federation on the user too much and I think this would be particularly problematic when it comes to iOS users who tend to prefer that things just work intuitively.  
I propose you provide a default instance for signing up/logging in. The user only needs to use '@' if they are not on or do not want to sign up to the default instance.  
  
While I am inclined to suggest mastodon.social be the default instance because it's the flagship instance it'd be more appropriate that a new one or reliable smaller one is used in order to avoid centralisation.

**Comment by AaronLMGoodwin** [comment]
You could do a sort of two-part form in the same line like: 

`[username] @ [instance]` 

They type in their username and then when instance is selected there's a default, or as they type it searches the list. 

I also really like the way places like Tumblr do it where login and signup are the same form. That reduces a lot of friction, I imagine.

**Comment by DagAgren** [comment]
I do not have the resources to run an instance, nor any interest in doing so, unfortunately. Mastodon.social regularly shuts down registrations due to being overloaded.
