### ISSUE TITLE
Reply to a boost does not include original poster’s handle

### ISSUE THREAD

**Issue by ticky** [DagAgren/toot#88]
Replying to a boosted toot currently populates the reply field with the handle of the booster only. This means, weirdly enough, that you can compose a toot which is in reply to another toot, but does not actually mention either the poster or the booster.

Example toot: https://cybre.space/@ticky/100561097473125563

**Comment by ticky** [comment]
Related but possibly the same bug: toots boosted by you show an “add another” button which will submit a reply to nobody

**Comment by DagAgren** [comment]
I think I fixed the second in development already.

**Comment by DagAgren** [comment]
You'd think this would be a small fix, huh.

Nope, required a big refactoring because the code wasn't really structured to keep track of rebloggers.
