### ISSUE TITLE
App cannot authenticate to mastodon.cloud

### ISSUE THREAD

**Issue by yonomitt** [DagAgren/toot#90]
The app cannot seem to authenticate me to mastodon.cloud.

I tap `Home`, then `Start Authentication`.

I then enter my mastodon.cloud login and it asks me to authorize the app. I authorize and then am returned to the screen with `Start Authentication`, but below is a message:

`⚠ Wrong password or email`

Tapping on `Start Authentication` again does not help.

**Comment by yonomitt** [comment]
When I log into mastodon.cloud via a browser, I can see that Toot! is an authorized app.

**Comment by mskblackbelt** [comment]
+1
I can log in with mastodon.social just fine, but mastodon.cloud throws an authentication error.

**Comment by alexanderweiss** [comment]
I'm having the same problem. And, although the error message is different, I'm also having trouble authorising Whalebird.

**Comment by DagAgren** [comment]
What version is mastodon.cloud on? Could someone contact the admin there to see if they are doing anything unusual?

**Comment by alexanderweiss** [comment]
It's on v2.4.3. Anything specific I should ask about?

**Comment by DagAgren** [comment]
No, I don't know at all why it would fail to work when all other instances seem fine.

**Comment by DagAgren** [comment]
This comment seems to say other clients are failing to authenticate too: 
https://mastodon.cloud/@alexanderweiss/100565983455127707

So it's probably a serverside issue. I'll leave this open for now so people can find the information. If anyone manages to log in successfully, let me know and I'll close this.

**Comment by mathowie** [comment]
Same here. Here’s a screencast of the errors https://www.dropbox.com/s/2hlerbxc7gw0fau/IMG_3583.TRIM.MOV?dl=0

**Comment by yonomitt** [comment]
For reference here are the related issues opened against `mastodon` and `doorkeeper`:

https://github.com/tootsuite/mastodon/pull/8231
 
https://github.com/doorkeeper-gem/doorkeeper/issues/1130

**Comment by yonomitt** [comment]
Mastodon has updated with a temporary fix until a permanent fix can be merged to doorkeeper. 

I can now authenticate to mastodon.cloud in Toot!

**Comment by rodrigoaraujo01** [comment]
I'm experiencing exactly the same thing as the OP. Any ways to reopen this?

**Comment by DagAgren** [comment]
It's not an issue in Toot!, it's a serverside issue.

**Comment by mathowie** [comment]
The last Testflight build re-introduced the bug. It was working fine until
I updated Toot a couple nights ago, and now can't login.

**Comment by rodrigoaraujo01** [comment]
Did something change in the authorization on the latest build?

**Comment by DagAgren** [comment]
Again: This is not a Toot! bug, it is a serverside issue.

**Comment by DagAgren** [comment]
Hmm. Looks like this is caused by the authentication update on Mastodon returning slightly different data than before. So I CAN work around it client side. I'll push out an update.
