### ISSUE TITLE
Feature request: allow pasting images into new toot screen

### ISSUE THREAD

**Issue by ticky** [DagAgren/toot#91]
Some other similar social apps accept images pasted from the clipboard, which works well for copying images from Safari, or from the screenshot editor in recent versions of iOS, without saving to the gallery (which sometimes puts the image far, far back in history if it has creation date metadata!)

This is generally done using the normal text-style paste function and UI (the little dark grey fallout) but I’ve also seen buttons explicitly for pasting the image.

This would be a nice thing to have here!

**Comment by AaronLMGoodwin** [comment]
Not to mention GIFs

**Comment by ashfurrow** [comment]
It would be _extra_ cool if when you tapped the "toot" button at the bottom, "copied image" was an option 😻

**Comment by DagAgren** [comment]
Depends on https://github.com/DagAgren/toot/issues/208

**Comment by DagAgren** [comment]
Added a paste button to the new toot screen that will paste images, too. I considered adding a button to the bottom menu, but I decided against it since there is at least one more button planned for there and it will get a bit too crowded.
