### ISSUE TITLE
Feature request: copy toot text

### ISSUE THREAD

**Issue by ticky** [DagAgren/toot#96]
This would be useful for translation in a third party app, and for copying weird Unicode art 😅

**Comment by AaronLMGoodwin** [comment]
I also frequently use this when I notice a typo in a toot (don't tell anybody I make typos, I'm a proud soul).

**Comment by bong0** [comment]
In the current version i cannot select a toot’s text. Is this supposed to work?

**Comment by JanJastrow** [comment]
@bong0 
1. Open a toot in 'single toot view'
2. tap 'MORE…'
3. tap 'Copy toot text'
4. ???
5. Profit!

**Comment by bong0** [comment]
@JanJastrow sorry my description was not complete enough.
My goal is to look up single words I don't understand (long tap, "look up")
