### ISSUE TITLE
Feature request: sharing extension

### ISSUE THREAD

**Issue by ticky** [DagAgren/toot#97]
The ability to post images from, for instance, the Photos app, would be a welcome addition!

**Comment by DagAgren** [comment]
At some future point, probably. Lots of other things hire in priority right now, though.

**Comment by ticky** [comment]
Yep, totally fair! :)

**Comment by debbiegoldsmith** [comment]
+1 for a sharing extension.

**Comment by DagAgren** [comment]
Depends on https://github.com/DagAgren/toot/issues/208

**Comment by dahlia** [comment]
Besides sharing images, it would be comfortable if it is possible to share links from other apps like Safari and Reddit.

**Comment by lamnatos** [comment]
+1 for a robust sharing extension. I'd love to be able to share links from Safari, esp. if it could also use the currently selected text as a snippet.
